"""
visualize_correlations.py — Cicada 3301 / Liber Primus
Full scan of all CSV/TXT files generated by the C++ tools with SHA-256 hash caching.
If the file size in bytes and the SHA-256 haven't changed since the last run,
that file's analysis is automatically skipped.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import re
import json
import hashlib
import glob

from sklearn.decomposition import PCA
import numpy as np
import networkx as nx
from scipy.stats import zscore
from scipy.spatial.distance import pdist, squareform
from networkx.algorithms.community import louvain_communities, modularity

try:
    import ruptures as rpt
except ImportError:
    rpt = None

# ---------------------------------------------------------------------------
# SHA-256 Hash Cache System
# ---------------------------------------------------------------------------

CACHE_DIR  = "../output/.cache"
CACHE_FILE = os.path.join(CACHE_DIR, "file_hashes.json")

def _load_cache() -> dict:
    """Load the JSON of persisted file hashes from disk."""
    os.makedirs(CACHE_DIR, exist_ok=True)
    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}
    return {}

def _save_cache(cache: dict) -> None:
    """Persist the JSON of file hashes to disk."""
    os.makedirs(CACHE_DIR, exist_ok=True)
    with open(CACHE_FILE, "w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2)

def _file_fingerprint(path: str) -> dict:
    """Return file size in bytes and SHA-256 hex of a file."""
    size = os.path.getsize(path)
    sha  = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            sha.update(chunk)
    return {"size": size, "sha256": sha.hexdigest()}

def needs_processing(path: str, cache: dict) -> bool:
    """
    Return True if the file needs (re)processing.
    Return False if size and SHA-256 match the previous record.
    """
    if not os.path.exists(path):
        return False
    fp = _file_fingerprint(path)
    prev = cache.get(os.path.abspath(path))
    if prev and prev.get("size") == fp["size"] and prev.get("sha256") == fp["sha256"]:
        print(f"[CACHE HIT] {os.path.basename(path)} - unchanged, skipping.")
        return False
    return True

def mark_processed(path: str, cache: dict) -> None:
    """Record the current fingerprint of the file in the cache."""
    if os.path.exists(path):
        cache[os.path.abspath(path)] = _file_fingerprint(path)

# ---------------------------------------------------------------------------
# Math helpers
# ---------------------------------------------------------------------------

def calculate_benford_dist(data):
    """Calcula a distribuição do primeiro dígito para comparar com a Lei de Benford."""
    digits = [int(str(abs(x))[0]) for x in data if x != 0]
    if not digits: return np.zeros(9)
    counts = np.bincount(digits, minlength=10)[1:]
    return counts / counts.sum()

BENFORD_IDEAL = np.log10(1 + 1/np.arange(1, 10))

def is_prime(n: int) -> bool:
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

def get_fibonacci(max_val: int) -> list:
    fibs = [1, 2]
    while fibs[-1] < max_val:
        fibs.append(fibs[-1] + fibs[-2])
    return fibs

def find_repeating_sequences(deltas: list, n: int = 3) -> dict:
    """Search for repeating n-grams of deltas."""
    sequences: dict = {}
    for i in range(len(deltas) - n + 1):
        seq = tuple(deltas[i : i + n])
        sequences[seq] = sequences.get(seq, 0) + 1
    return {k: v for k, v in sequences.items() if v > 1}

# ---------------------------------------------------------------------------
# Generate textual report with suspicion score
# ---------------------------------------------------------------------------

def generate_textual_report(df, csv_file: str, principal_components=None) -> None:
    report_file = csv_file.replace(".csv", "_report.txt")

    G = nx.from_pandas_adjacency(df)
    mask = np.ones(df.shape, dtype=bool)
    np.fill_diagonal(mask, 0)

    corr_pairs = df.where(mask).stack().reset_index()
    corr_pairs.columns = ["Page_A", "Page_B", "Correlation"]
    top_corrs  = corr_pairs.sort_values("Correlation", ascending=False).head(20)
    all_values = corr_pairs["Correlation"].values
    page_means = df.where(mask).mean()

    degree_cent  = nx.degree_centrality(G)
    betweenness  = nx.betweenness_centrality(G)
    communities  = louvain_communities(G, weight="weight", resolution=1, seed=42)
    mod          = modularity(G, communities, weight="weight")
    z_scores_corr = zscore(page_means)
    z_series     = pd.Series(z_scores_corr, index=page_means.index)

    features_path = os.path.join(os.path.dirname(csv_file), "page_features.csv")
    features_df   = None
    if os.path.exists(features_path):
        features_df = pd.read_csv(features_path, index_col=0)

    outliers = z_series[z_series < -2]

    with open(report_file, "w", encoding="utf-8") as f:
        f.write(f"=== ADVANCED STATISTICAL REPORT: {os.path.basename(csv_file)} ===\n\n")
        f.write(f"Overall Mean Correlation: {np.mean(all_values):.4f}\n")
        f.write(f"Modularity (Louvain): {mod:.4f} ")
        if   mod < 0.2: f.write("(Weak Structure)\n")
        elif mod < 0.4: f.write("(Moderate Structure)\n")
        else:           f.write("(Strong Clusters)\n")
        f.write(f"Median: {np.median(all_values):.4f}\n")
        f.write(f"Std Dev: {np.std(all_values):.4f}\n")
        f.write(f"Variance: {np.var(all_values):.4f}\n")
        f.write(f"Max Value (excl. diagonal): {np.max(all_values):.4f}\n")
        f.write(f"Min Value: {np.min(all_values):.4f}\n\n")

        f.write("--- TOP 20 STRONGEST CORRELATIONS ---\n")
        for _, row in top_corrs.iterrows():
            f.write(f"{row['Page_A']} <-> {row['Page_B']}: {row['Correlation']:.6f}\n")

        f.write("\n--- NETWORK CENTRALITY (Bridge/Transit Pages) ---\n")
        for page in sorted(degree_cent, key=degree_cent.get, reverse=True)[:10]:
            f.write(f"{page:10}: Degree={degree_cent[page]:.4f} Betweenness={betweenness[page]:.4f}\n")

        f.write("\n--- DETECTED COMMUNITIES (Louvain) ---\n")
        for i, c in enumerate(communities):
            f.write(f"Cluster {i+1}: {len(c)} pages ({', '.join(list(c)[:5])}...)\n")

        f.write("\n--- HUB PAGES (High mean similarity with the book) ---\n")
        hub_pages = df.where(mask).mean().sort_values(ascending=False).head(5)
        for page, val in hub_pages.items():
            f.write(f"{page}: Mean correlation {val:.4f}\n")

        f.write("\n--- STATISTICAL OUTLIERS (Z-Score < -2) ---\n")
        if outliers.empty:
            f.write("No statistical outliers detected.\n")
        else:
            for page, val in outliers.items():
                f.write(f"{page}: Z={val:.2f}\n")

        z_pca_scores: dict = {}
        if principal_components is not None:
            dist_pca = np.sqrt(
                principal_components[:, 0] ** 2 + principal_components[:, 1] ** 2
            )
            idx_ext = np.argsort(dist_pca)[::-1][:10]
            f.write("\n--- PAGES FAR FROM PCA CENTER (Language anomalies) ---\n")
            for i in idx_ext:
                f.write(f"{df.index[i]:10}: Distância {dist_pca[i]:.3f}\n")
            z_pca_vals = zscore(dist_pca)
            for i, name in enumerate(df.index):
                z_pca_scores[name] = z_pca_vals[i]

        f.write("\n=== TOP SUSPICIOUS PAGES (PRIORITY SCORE) ===\n")
        heuristic_path = os.path.join(os.path.dirname(csv_file), "heuristic_scores.csv")
        h_df = pd.read_csv(heuristic_path, index_col=0) if os.path.exists(heuristic_path) else None

        suspicion_list = []
        for name in df.index:
            z_corr = abs(z_series[name])
            z_pca  = abs(z_pca_scores.get(name, 0))
            cent   = betweenness.get(name, 0)
            score  = (z_corr * 0.2) + (z_pca * 0.4) + (cent * 5.0)

            if features_df is not None and name in features_df.index:
                f_row    = features_df.loc[name]
                ioc_dev  = abs(f_row.get("IoC",     0.034) - 0.067)
                ent_dev  = abs(f_row.get("Entropy", 4.3)   - 4.25)   # noqa: F841
                lrs_bonus = f_row.get("LRS", 0) * 0.5
                score = 0.2 * z_corr + 0.2 * z_pca + 0.3 * ioc_dev + 0.2 * cent + lrs_bonus

            suspicion_list.append((name, score))

        suspicion_list.sort(key=lambda x: x[1], reverse=True)
        for name, score in suspicion_list[:15]:
            f.write(f"{name:12} -> Score: {score:.2f}\n")

        f.write("\n--- INTERNAL STRUCTURE ANALYSIS ---\n")
        high_corr_threshold = 0.8
        dense_count = np.sum(all_values > high_corr_threshold)
        density = dense_count / len(all_values)
        f.write(f"High Correlation Density (>0.8): {density * 100:.2f}%\n")
        f.write(
            "Note: A high density suggests that a large portion of the book "
            "shares the same ciphering algorithm.\n"
        )

    print(f"Textual report saved: {report_file}")

# ---------------------------------------------------------------------------
# plot_correlation_matrix — heatmap + clustermap + network + PCA
# ---------------------------------------------------------------------------

def plot_correlation_matrix(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return

    if not os.path.exists(csv_file):
        print(f"File not found: {csv_file}")
        return

    df = pd.read_csv(csv_file, index_col=0)
    principal_components = None
    pca = None
    if df.shape[0] > 1:
        pca = PCA(n_components=2)
        principal_components = pca.fit_transform(df)

    generate_textual_report(df, csv_file, principal_components)

    # Cosine distance matrix
    dist_mat = squareform(pdist(df.values, metric="cosine"))
    plt.figure(figsize=(12, 10))
    sns.heatmap(dist_mat, cmap="viridis", center=None, square=True)
    plt.title(f"Distance Matrix (Cosine): {os.path.basename(csv_file)}")
    plt.savefig(csv_file.replace(".csv", "_dist_cosine.png"), dpi=300, bbox_inches="tight")
    plt.close()

    sns.set_theme(style="white")

    # Simple heatmap
    plt.figure(figsize=(14, 12))
    sns.heatmap(
        df, cmap="RdYlBu_r", center=0, square=True,
        linewidths=0.5, cbar_kws={"shrink": 0.8},
    )
    plt.title(f"Correlation Matrix: {csv_file}", fontsize=16)
    plt.savefig(csv_file.replace(".csv", "_heatmap.png"), dpi=300, bbox_inches="tight")
    print(f"Heatmap saved: {csv_file.replace('.csv','_heatmap.png')}")
    plt.close()

    # Hierarchical clustermap
    cg = sns.clustermap(  # noqa: F841
        df, cmap="RdYlBu_r", center=0, method="ward", figsize=(15, 15), linewidths=0.5
    )
    plt.title(f"Hierarchical Clustering: {csv_file}", fontsize=16, pad=100)
    plt.savefig(csv_file.replace(".csv", "_cluster.png"), dpi=300, bbox_inches="tight")
    print(f"Clustermap saved: {csv_file.replace('.csv','_cluster.png')}")
    plt.close()

    # Network graph (adaptive threshold)
    try:
        G = nx.Graph()
        mask_net = np.ones(df.shape, dtype=bool)
        np.fill_diagonal(mask_net, 0)
        all_corr_vals = df.where(mask_net).stack().values
        threshold = float(np.mean(all_corr_vals) + 1.5 * np.std(all_corr_vals))
        threshold = max(0.7, min(threshold, 0.98))

        for i in range(len(df.index)):
            for j in range(i + 1, len(df.columns)):
                if df.iloc[i, j] > threshold:
                    G.add_edge(df.index[i], df.columns[j], weight=df.iloc[i, j])

        if len(G.nodes) > 0:
            plt.figure(figsize=(12, 12))
            pos     = nx.spring_layout(G, k=0.5, iterations=50)
            edges   = G.edges()
            weights = [G[u][v]["weight"] * 2 for u, v in edges]
            nx.draw_networkx_nodes(G, pos, node_size=700, node_color="skyblue", alpha=0.8)
            nx.draw_networkx_edges(G, pos, edgelist=edges, width=weights, edge_color="gray", alpha=0.5)
            nx.draw_networkx_labels(G, pos, font_size=10, font_family="sans-serif")
            plt.title(f"Network of Highly Correlated Pages (>{threshold:.2f})", fontsize=14)
            plt.savefig(csv_file.replace(".csv", "_network.png"), dpi=300, bbox_inches="tight")
            plt.close()
            print(f"Network graph saved: {csv_file.replace('.csv','_network.png')}")
    except Exception as exc:
        print(f"Error generating network graph: {exc}")

    # PCA scatter
    if pca is not None and principal_components is not None:
        try:
            pca_df = pd.DataFrame(
                principal_components,
                columns=["principal_component_1", "principal_component_2"],
            )
            pca_df["Page"] = df.index
            plt.figure(figsize=(12, 10))
            sns.scatterplot(
                x="principal_component_1", y="principal_component_2",
                hue="Page", data=pca_df, s=100,
            )
            plt.title(f"Correlation PCA: {csv_file}", fontsize=16)
            plt.xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.2f}%)")
            plt.ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.2f}%)")
            for _, row in pca_df.iterrows():
                plt.text(
                    row["principal_component_1"] + 0.01,
                    row["principal_component_2"] + 0.01,
                    row["Page"], fontsize=8, ha="left", va="bottom",
                )
            plt.savefig(csv_file.replace(".csv", "_pca.png"), dpi=300, bbox_inches="tight")
            print(f"PCA plot saved: {csv_file.replace('.csv','_pca.png')}")
            plt.close()
        except Exception as exc:
            print(f"Error generating PCA for {csv_file}: {exc}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_delta_histograms — interrupt_deltas.csv
# ---------------------------------------------------------------------------

def plot_delta_histograms(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    print(f"\n{'='*60}")
    print(f"--- DEEP DELTA ANALYSIS: {os.path.basename(csv_file)} ---")
    print("=" * 60)

    all_deltas = df["Delta"].tolist()
    max_d      = int(df["Delta"].max())
    fibs       = get_fibonacci(max_d)
    top_deltas = df["Delta"].value_counts().head(10)

    print("\n[1. Mathematical properties of top deltas]")
    for delta, count in top_deltas.items():
        d_int      = int(delta)
        percentage = (count / len(df)) * 100
        props      = []
        if d_int in fibs:     props.append("FIBONACCI")
        if is_prime(d_int):   props.append("PRIME")
        prop_str = f"({', '.join(props)})" if props else ""
        print(f"  Delta {d_int:3d}: {count:3d} times ({percentage:5.2f}%) {prop_str}")

    print("\n[2. Cycle detection (repeating sequences)]")
    for n in range(3, 6):
        repeats = find_repeating_sequences(all_deltas, n)
        if repeats:
            sorted_repeats = sorted(repeats.items(), key=lambda x: x[1], reverse=True)[:5]
            print(f"  Top {n}-grams:")
            for seq, count in sorted_repeats:
                print(f"    {list(seq)} -> {count} occurrences")

    print("\n[3. Suggestion for Skip-Vigenere attack]")
    if len(top_deltas) >= 3:
        suggested = [int(d) for d in top_deltas.index[:5]]
        print(f"  Try using this jump sequence: {suggested}")

    # Histogram per page (if Page column exists)
    if "Page" in df.columns:
        for page_name, grp in df.groupby("Page"):
            plt.figure(figsize=(10, 4))
            max_val = int(grp["Delta"].max())
            sns.histplot(data=grp, x="Delta", bins=range(0, max_val + 2), kde=False, color="teal")
            plt.title(f"Deltas — {page_name}", fontsize=13)
            plt.xlabel("Delta")
            plt.ylabel("Occurrences")
            clean = str(page_name).replace(" ", "_")
            out   = csv_file.replace(".csv", f"_hist_{clean}.png")
            plt.savefig(out, dpi=200, bbox_inches="tight")
            plt.close()

    # Histograma global
    plt.figure(figsize=(12, 6))
    sns.histplot(data=df, x="Delta", bins=range(0, max_d + 2), kde=False, color="teal")
    plt.title("Delta Frequency Distribution (Skip Intervals)", fontsize=14)
    plt.xlabel("Delta (distance between interrupts)")
    plt.ylabel("Occurrences")
    out_global = csv_file.replace(".csv", "_histogram.png")
    plt.savefig(out_global, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"\nHistogram saved: {out_global}")

    # TopDelta por page (se coluna TopDelta existir)
    if "TopDelta" in df.columns and "Page" in df.columns:
        top_df = df.sort_values("TopDelta", ascending=False).drop_duplicates("Page")
        plt.figure(figsize=(12, max(5, len(top_df) * 0.35)))
        plt.barh(top_df["Page"].astype(str), top_df["TopDelta"], color="#76b7b2")
        plt.xlabel("TopDelta (largest interval on page)")
        plt.title("Pages with largest interrupt intervals")
        plt.tight_layout()
        out_top = csv_file.replace(".csv", "_topdelta.png")
        plt.savefig(out_top, dpi=200, bbox_inches="tight")
        plt.close()
        print(f"TopDelta plot saved: {out_top}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_gematria_analysis — gematria_sums.csv (NOVO)
# ---------------------------------------------------------------------------

def plot_gematria_analysis(csv_file: str, cache: dict) -> None:
    """Analyzes word numerological properties (Gematria)."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    out_dir = os.path.dirname(csv_file)

    # 1. Distribuição de Digital Roots (Frequência de 1 a 9)
    if 'DigitalRoot' in df.columns:
        plt.figure(figsize=(10, 6))
        sns.countplot(data=df, x='DigitalRoot', hue='DigitalRoot', palette='deep', legend=False)
        plt.title('Distribution of Digital Roots (Gematria)', fontsize=14)
        plt.xlabel('Digital Root')
        plt.ylabel('Word Count')
        out_dr = csv_file.replace('.csv', '_digital_root_dist.png')
        plt.savefig(out_dr, dpi=200, bbox_inches='tight')
        plt.close()
        print(f'Digital root distribution saved: {out_dr}')

    # 2. Proporção de primos / fibonacci por página
    if 'IsPrime' in df.columns or 'IsFibonacci' in df.columns:
        page_stats = df.groupby('Page').agg({
            'IsPrime': 'mean' if 'IsPrime' in df.columns else (lambda x: 0),
            'IsFibonacci': 'mean' if 'IsFibonacci' in df.columns else (lambda x: 0),
        })
        plt.figure(figsize=(12, 6))
        cols = [c for c in ['IsPrime', 'IsFibonacci'] if c in page_stats.columns]
        if cols:
            page_stats[cols].plot(kind='bar', stacked=False, figsize=(14, 6), color=['#e15759', '#76b7b2'][:len(cols)])
            plt.title('Proportion of Prime and Fibonacci Sums per Page', fontsize=14)
            plt.ylabel('Proportion (0.0 - 1.0)')
            out_stats = csv_file.replace('.csv', '_page_stats.png')
            plt.savefig(out_stats, dpi=200, bbox_inches='tight')
            plt.close()
            print(f'Prime/Fibonacci proportions saved: {out_stats}')

    # 3. Lei de Benford na soma das palavras (primeiro dígito)
    if 'Sum' in df.columns:
        actual_benford = calculate_benford_dist(df['Sum'].dropna())
        x = np.arange(1, 10)
        plt.figure(figsize=(10, 6))
        plt.bar(x - 0.2, actual_benford, width=0.4, label='Gematria Sums', color='#4e79a7')
        plt.bar(x + 0.2, BENFORD_IDEAL, width=0.4, label='Benford Ideal', color='#e15759', alpha=0.6)
        plt.xticks(x)
        plt.title("Benford's Law Analysis: Word Sums (First Digit)")
        plt.xlabel('First Digit')
        plt.ylabel('Frequency')
        plt.legend()
        out_benford = csv_file.replace('.csv', '_benford.png')
        plt.savefig(out_benford, dpi=200, bbox_inches='tight')
        plt.close()
        print(f'Benford plot saved: {out_benford}')

    mark_processed(csv_file, cache)


# ---------------------------------------------------------------------------
# Doublet runic analysis: load CSV produced by C++ and analyze
# ---------------------------------------------------------------------------

def load_doublet_csv(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        print(f"Doublet CSV not found: {path}")
        return pd.DataFrame()
    df = pd.read_csv(path)
    return df


def analyze_doublet_overview(df: pd.DataFrame, out_dir: str) -> None:
    """Produce summary CSVs and simple plots: histogram of doublet ratios, top runes, run-length distribution."""
    if df.empty: return
    os.makedirs(out_dir, exist_ok=True)

    # Histogram of doublet ratios
    plt.figure(figsize=(10,6))
    sns.histplot(df['DoubletRatio'].dropna(), bins=50, color='#4e79a7')
    plt.title('Distribution of Doublet Ratios (per page)')
    plt.xlabel('Doublet Ratio')
    plt.savefig(os.path.join(out_dir, 'doublet_ratio_hist.png'), dpi=200, bbox_inches='tight')
    plt.close()

    # Top runes by total doublet occurrences
    rune_totals = {}
    for s in df['DoubletRuneCounts'].dropna().astype(str):
        s = s.strip('{}')
        if not s: continue
        for part in s.split(';'):
            k,v = part.split(':')
            rune = int(k); cnt = int(v)
            rune_totals[rune] = rune_totals.get(rune,0) + cnt
    rune_series = pd.Series(rune_totals).sort_values(ascending=False)
    rune_series.to_csv(os.path.join(out_dir, 'doublet_rune_totals.csv'), header=['Count'])

    plt.figure(figsize=(10,6))
    rune_series.head(30).plot(kind='bar', color='#e15759')
    plt.title('Top runes by doublet occurrences (global)')
    plt.xlabel('Rune Index')
    plt.ylabel('Doublet Count')
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, 'doublet_top_runes.png'), dpi=200)
    plt.close()

    # Run-length distribution
    runs = []
    for s in df['RunLengths'].dropna().astype(str):
        if s.strip() == '': continue
        for v in s.split(';'):
            runs.append(int(v))
    if runs:
        plt.figure(figsize=(10,6))
        sns.histplot(runs, bins=range(1, max(runs)+2), color='#76b7b2')
        plt.title('Run lengths distribution (consecutive repeated runes)')
        plt.xlabel('Run length')
        plt.ylabel('Occurrences')
        plt.savefig(os.path.join(out_dir, 'doublet_run_lengths.png'), dpi=200, bbox_inches='tight')
        plt.close()


def build_transition_matrix(df: pd.DataFrame):
    """Aggregate bigram counts from the CSV into a 29x29 matrix and return matrix and labels."""
    mat = np.zeros((29,29), dtype=int)
    pages = []
    for _, row in df.iterrows():
        pages.append(row['Page'])
        s = str(row['BigramCounts']).strip('{}')
        if s == '': continue
        for part in s.split(';'):
            if not part: continue
            kv = part.split(':')
            pair = kv[0]; cnt = int(kv[1])
            a,b = pair.split('-')
            ai = int(a); bi = int(b)
            if 0 <= ai < 29 and 0 <= bi < 29:
                mat[ai,bi] += cnt
    return mat, pages


def plot_transition_heatmap(mat: np.ndarray, out_path: str) -> None:
    plt.figure(figsize=(10,8))
    sns.heatmap(mat, cmap='magma', square=True)
    plt.title('Aggregated Rune Transition Counts (bigram)')
    plt.xlabel('Next rune')
    plt.ylabel('Current rune')
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    plt.close()


def analyze_doublet_sequences(df: pd.DataFrame, out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)
    mat, pages = build_transition_matrix(df)
    np.savetxt(os.path.join(out_dir, 'bigram_matrix.csv'), mat, delimiter=',', fmt='%d')
    plot_transition_heatmap(mat, os.path.join(out_dir, 'bigram_heatmap.png'))

    # Normalize to transition probabilities per-row and save
    row_sums = mat.sum(axis=1, keepdims=True)
    with np.errstate(divide='ignore', invalid='ignore'):
        prob = np.divide(mat, row_sums, out=np.zeros(mat.shape, dtype=float), where=row_sums!=0)
    np.savetxt(os.path.join(out_dir, 'bigram_prob_matrix.csv'), prob, delimiter=',', fmt='%.6f')

    # For resolved vs unresolved comparison, try to use page_features.csv if available
    features_path = os.path.join(os.path.dirname(out_dir), 'page_features.csv')
    resolved_mask = None
    if os.path.exists(features_path):
        feats = pd.read_csv(features_path, index_col=0)
        resolved = []
        for p in pages:
            if p in feats.index:
                # assume a column 'Known' exists or infer from IoC/heuristics: use has_known_solution mapping
                resolved.append(bool(feats.loc[p].get('Known', False)))
            else:
                resolved.append(False)
        resolved_mask = np.array(resolved, dtype=bool)

    # If we have resolved mask, aggregate separate matrices
    if resolved_mask is not None and resolved_mask.any():
        # rebuild per-page matrices and sum
        resolved_mat = np.zeros_like(mat)
        unresolved_mat = np.zeros_like(mat)
        for i, p in enumerate(pages):
            row = df.iloc[i]
            s = str(row['BigramCounts']).strip('{}')
            local = np.zeros_like(mat)
            if s != '':
                for part in s.split(';'):
                    if not part: continue
                    kv = part.split(':')
                    pair = kv[0]; cnt = int(kv[1])
                    a,b = pair.split('-')
                    ai = int(a); bi = int(b)
                    local[ai,bi] += cnt
            if resolved_mask[i]: resolved_mat += local
            else: unresolved_mat += local

        plot_transition_heatmap(resolved_mat, os.path.join(out_dir, 'bigram_heatmap_resolved.png'))
        plot_transition_heatmap(unresolved_mat, os.path.join(out_dir, 'bigram_heatmap_unresolved.png'))


def run_doublet_analysis_pipeline(cache: dict = None):
    if cache is None: cache = _load_cache()
    path = os.path.join('..', 'output', 'doublet_data.csv')
    if not needs_processing(path, cache):
        return
    df = load_doublet_csv(path)
    if df.empty:
        return
    out_dir = os.path.join('..', 'output', 'doublet_analysis')
    analyze_doublet_overview(df, out_dir)
    analyze_doublet_sequences(df, out_dir)
    mark_processed(path, cache)

# ---------------------------------------------------------------------------
# plot_unigram_distribution — liber_unigram_target.csv
# ---------------------------------------------------------------------------

def plot_unigram_distribution(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    plt.figure(figsize=(12, 6))
    sns.barplot(
        x="RuneIndex", y="Frequency", data=df,
        hue="RuneIndex", palette="magma", legend=False,
    )
    plt.title("Target Unigram Frequency (based on resolved pages)", fontsize=14)
    plt.xlabel("Rune Index (0-28)")
    plt.ylabel("Relative Frequency")
    out = csv_file.replace(".csv", "_dist.png")
    plt.savefig(out, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Unigram distribution plot saved: {out}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_heuristic_summary — heuristic_scores.csv
# ---------------------------------------------------------------------------

def plot_heuristic_summary(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    df_sorted     = df.sort_values("Fitness", ascending=False)
    cipher_colors = {"None": "#aaaaaa", "Shift": "#4e79a7", "Atbash": "#f28e2b"}
    colors        = [cipher_colors.get(c, "#59a14f") for c in df_sorted["BestCipher"]]

    fig, axes = plt.subplots(1, 2, figsize=(18, max(6, len(df_sorted) * 0.35)))

    axes[0].barh(df_sorted["Page"], df_sorted["Fitness"], color=colors)
    axes[0].set_xlabel("Fitness Score (JSD)", fontsize=12)
    axes[0].set_title("Heuristic Ranking: Pages closest to solved", fontsize=13)
    axes[0].axvline(x=df_sorted["Fitness"].mean(),  color="red",    linestyle="--", alpha=0.6)
    axes[0].axvline(x=df_sorted["Fitness"].mean() + df_sorted["Fitness"].std(),
                    color="orange", linestyle=":",  alpha=0.6)
    from matplotlib.patches import Patch
    legend_elements = [Patch(facecolor=v, label=k) for k, v in cipher_colors.items()]
    axes[0].legend(handles=legend_elements, loc="lower right", fontsize=9)

    scatter_colors = [cipher_colors.get(c, "#59a14f") for c in df["BestCipher"]]
    axes[1].scatter(
        df["IoC"], df["Fitness"],
        c=scatter_colors, s=60, alpha=0.8, edgecolors="white", linewidth=0.5,
    )
    axes[1].axvline(x=0.034, color="gray",  linestyle="--", alpha=0.5, label="Random IoC (1/29)")
    axes[1].axvline(x=0.067, color="green", linestyle="--", alpha=0.5, label="IoC texto simples")
    axes[1].set_xlabel("Baseline IoC", fontsize=12)
    axes[1].set_ylabel("Fitness Score", fontsize=12)
    axes[1].set_title("IoC vs Fitness — Attack map", fontsize=13)
    for _, row in df.iterrows():
        axes[1].annotate(
            str(row["Page"]), (row["IoC"], row["Fitness"]),
            fontsize=7, alpha=0.7, xytext=(3, 3), textcoords="offset points",
        )
    axes[1].legend(fontsize=9)

    plt.tight_layout()
    out = csv_file.replace(".csv", "_dashboard.png")
    plt.savefig(out, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Heuristic dashboard saved: {out}")

    # Vigenère key lengths
    if "BestVigenereKeyLen" in df.columns:
        vigenere_pages = df[df["BestVigenereKeyLen"] > 0].sort_values("BestVigenereKeyLen")
        if not vigenere_pages.empty:
            plt.figure(figsize=(10, max(4, len(vigenere_pages) * 0.4)))
            plt.barh(
                vigenere_pages["Page"].astype(str),
                vigenere_pages["BestVigenereKeyLen"],
                color="#76b7b2",
            )
            plt.xlabel("Estimated Vigenère key length", fontsize=12)
            plt.title("Pages with detected periodic pattern (possible Vigenère)", fontsize=13)
            plt.tight_layout()
            out_v = csv_file.replace(".csv", "_vigenere_keylens.png")
            plt.savefig(out_v, dpi=200, bbox_inches="tight")
            plt.close()
            print(f"Vigenère key lengths plot saved: {out_v}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_key_stream_analysis — key_stream_analysis.csv
# ---------------------------------------------------------------------------

def plot_key_stream_analysis(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    pages   = df["Page"].unique()
    n_pages = len(pages)
    if n_pages == 0:
        return

    max_pages_to_plot = 10 # Limit to 10 pages per image to avoid DecompressionBombError
    pages_to_plot = pages[:max_pages_to_plot]
    
    if n_pages > max_pages_to_plot:
        print(f"Warning: Only plotting the first {max_pages_to_plot} of {n_pages} pages in key stream analysis to prevent image size issues.")

    fig, axes = plt.subplots(len(pages_to_plot), 2, figsize=(16, 4 * len(pages_to_plot)), squeeze=False)
    fig.suptitle("Key Stream Analysis (Solved Pages)", fontsize=15, y=1.01)

    # Iterate only over selected pages to plot
    for i, page in enumerate(pages_to_plot):
        page_data = df[df["Page"] == page]
        # Filter out "UNRESOLVED" markers before converting to float
        numeric_series = page_data[page_data["KeyValue"] != "UNRESOLVED"]["KeyValue"]
        stream = numeric_series.values.astype(float)
        if len(stream) < 10:
            axes[i][0].set_title(f"{page} — stream too short")
            axes[i][1].set_title("")
            continue

        max_lag   = min(len(stream) // 2, 60)
        lags      = np.arange(1, max_lag + 1)
        autocorrs = []
        for lag in lags:
            s1, s2 = stream[:-lag], stream[lag:]
            if np.std(s1) == 0 or np.std(s2) == 0:
                autocorrs.append(0.0)
            else:
                autocorrs.append(np.corrcoef(s1, s2)[0, 1])

        conf = 1.96 / np.sqrt(len(stream))
        axes[i][0].bar(lags, autocorrs, color="steelblue", alpha=0.7)
        axes[i][0].axhline(y=0,     color="black", linewidth=0.8)
        axes[i][0].axhline(y= conf, color="red", linestyle="--", alpha=0.5, label=f"±95% ({conf:.3f})")
        axes[i][0].axhline(y=-conf, color="red", linestyle="--", alpha=0.5)
        axes[i][0].set_title(f"{page} — Key Stream Autocorrelation", fontsize=11)
        axes[i][0].set_xlabel("Lag")
        axes[i][0].set_ylabel("Correlation")
        axes[i][0].legend(fontsize=8)

        fft_vals          = np.abs(np.fft.rfft(stream - stream.mean()))
        freqs             = np.fft.rfftfreq(len(stream))
        fft_vals[0]       = 0
        dominant_freq_idx = np.argmax(fft_vals[1:]) + 1
        dominant_period   = (
            int(round(1.0 / freqs[dominant_freq_idx])) if freqs[dominant_freq_idx] > 0 else 0
        )
        axes[i][1].plot(freqs[1:], fft_vals[1:], color="darkorange", linewidth=1)
        if dominant_freq_idx < len(freqs):
            axes[i][1].axvline(
                x=freqs[dominant_freq_idx], color="red", linestyle="--", alpha=0.7,
                label=f"Dominant period: {dominant_period}",
            )
        axes[i][1].set_title(f"{page} — Key Stream FFT", fontsize=11)
        axes[i][1].set_xlabel("Frequency")
        axes[i][1].set_ylabel("Magnitude")
        axes[i][1].legend(fontsize=8)

    plt.tight_layout()
    out = csv_file.replace(".csv", "_fft_autocorr.png")
    plt.savefig(out, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"FFT/Autocorrelation analysis saved: {out}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_page_features — page_features.csv  ← NEW
# ---------------------------------------------------------------------------

def plot_page_features(csv_file: str, cache: dict) -> None:
    """IoC vs Entropy scatter, Fitness ranking e métricas avançadas."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    # 1. Scatter IoC × Entropy colored by Fitness
    plt.figure(figsize=(12, 8))
    s = df.get('Fitness', None)
    sizes = None
    if 'Length' in df.columns and df['Length'].max() > 0:
        sizes = df['Length'] / df['Length'].max() * 300 + 40
    else:
        sizes = 80
    sc = plt.scatter(
        df['IoC'], df['Entropy'],
        c=s if s is not None else 'gray', cmap='viridis', s=sizes,
        alpha=0.85, edgecolors='white', linewidth=0.4,
    )
    if s is not None:
        plt.colorbar(sc, label='Fitness Score')
    plt.axvline(x=0.034, color='red', linestyle='--', alpha=0.6, label='Random IoC')
    plt.axvline(x=0.067, color='green', linestyle='--', alpha=0.6, label='Plaintext IoC')
    for _, row in df.iterrows():
        try:
            plt.annotate(str(row['Page']), (row['IoC'], row['Entropy']), fontsize=7, alpha=0.8)
        except Exception:
            pass
    plt.title('Crypto-Signature: Entropy vs Index of Coincidence', fontsize=14)
    plt.xlabel('Index of Coincidence (IoC)')
    plt.ylabel('Entropy (Bits per Rune)')
    plt.legend()
    plt.grid(True, alpha=0.2)
    out_scatter = csv_file.replace('.csv', '_entropy_ioc.png')
    plt.savefig(out_scatter, dpi=300, bbox_inches='tight')
    plt.close()
    print(f'Plot Entropy vs IoC saved: {out_scatter}')

    # 2. Fitness ranking (bars)
    if 'Fitness' in df.columns:
        df_sorted = df.sort_values('Fitness', ascending=False)
        plt.figure(figsize=(14, max(6, len(df_sorted) * 0.35)))
        plt.barh(df_sorted['Page'].astype(str), df_sorted['Fitness'], color='#4e79a7')
        plt.xlabel('Advanced Fitness Score')
        plt.title('Fitness Ranking per Page')
        plt.tight_layout()
        out_fit = csv_file.replace('.csv', '_fitness_ranking.png')
        plt.savefig(out_fit, dpi=200, bbox_inches='tight')
        plt.close()
        print(f'Fitness ranking saved: {out_fit}')

    # 3. Optional Parallel Coordinates (plotly) — expanded for high-density detail
    try:
        potential_cols = [
            'Length', 'IoC', 'Entropy', 'ChiSquare', 'Fitness', 
            'BigramIoC', 'NumInterrupts', 'GpsSumMean', 'TopDelta', 'LRS'
        ]
        cols_to_use = [c for c in potential_cols if c in df.columns]
        
        if len(cols_to_use) > 2:
            import plotly.express as px
            
            df_plot = df.copy()
            # Add Page Number axis for easier identification of which line is which page
            if 'Page' in df_plot.columns:
                df_plot['PageNum'] = df_plot['Page'].apply(
                    lambda x: int(re.findall(r'\d+', str(x))[0]) if re.findall(r'\d+', str(x)) else 0
                )
                if 'PageNum' not in cols_to_use:
                    cols_to_use.insert(0, 'PageNum')

            fig = px.parallel_coordinates(
                df_plot, 
                color='Fitness' if 'Fitness' in df_plot.columns else None,
                dimensions=cols_to_use,
                color_continuous_scale=px.colors.sequential.Plasma,
                title='Liber Primus: Multi-Dimensional Page Metrics Analysis (Absolute Values)'
            )
            
            fig.update_layout(
                height=850,
                margin=dict(l=80, r=80, t=100, b=80),
                font=dict(size=12)
            )

            out_parallel = csv_file.replace('.csv', '_parallel.html')
            fig.write_html(out_parallel)
            print(f'Parallel coordinates saved (HTML): {out_parallel}')
    except Exception as e:
        print(f'Error in parallel plot: {e}')

    # 4. Chi-Square ranking
    if 'ChiSquare' in df.columns:
        df_chi = df.sort_values('ChiSquare', ascending=False)
        plt.figure(figsize=(14, max(6, len(df_chi) * 0.35)))
        plt.barh(df_chi['Page'].astype(str), df_chi['ChiSquare'], color='#e15759')
        plt.xlabel('Chi-Square (distance from uniform)')
        plt.title('Chi-Square Ranking per Page (higher = further from noise)')
        plt.tight_layout()
        out_chi = csv_file.replace('.csv', '_chi_ranking.png')
        plt.savefig(out_chi, dpi=200, bbox_inches='tight')
        plt.close()
        print(f'Chi-Square ranking saved: {out_chi}')

    # 5. GP Sum Mean
    if 'GpsSumMean' in df.columns:
        df_gps = df.sort_values('GpsSumMean', ascending=False)
        plt.figure(figsize=(14, max(6, len(df_gps) * 0.35)))
        plt.barh(df_gps['Page'].astype(str), df_gps['GpsSumMean'], color='#76b7b2')
        plt.xlabel('GP Sum Mean (average word value)')
        plt.title('GP Sum per Page')
        plt.tight_layout()
        out_gps = csv_file.replace('.csv', '_gps_mean.png')
        plt.savefig(out_gps, dpi=200, bbox_inches='tight')
        plt.close()
        print(f'GPS Sum ranking saved: {out_gps}')

    # 6. BigramIoC
    if 'BigramIoC' in df.columns:
        df_b = df.sort_values('BigramIoC', ascending=False)
        plt.figure(figsize=(14, max(6, len(df_b) * 0.35)))
        plt.barh(df_b['Page'].astype(str), df_b['BigramIoC'], color='#f1ce63')
        plt.xlabel('Bigram IoC')
        plt.title('Bigram Index of Coincidence per Page')
        plt.tight_layout()
        out_b = csv_file.replace('.csv', '_bigram_ioc.png')
        plt.savefig(out_b, dpi=200, bbox_inches='tight')
        plt.close()
        print(f'Bigram IoC ranking saved: {out_b}')

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_friedman_scan — friedman_scan.csv  ← NOVO
# ---------------------------------------------------------------------------

def plot_friedman_scan(csv_file: str, cache: dict) -> None:
    """Heatmap of periodic IoC by page and candidate key length."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    # Espera colunas: Page, KeyLen, AvgColIoC
    if not {"Page", "KeyLen", "AvgColIoC"}.issubset(df.columns):
        print(f"friedman_scan.csv missing expected columns — skipping heatmap.")
        return

    pivot = df.pivot(index="Page", columns="KeyLen", values="AvgColIoC")
    plt.figure(figsize=(max(12, len(pivot.columns) * 0.6), max(8, len(pivot) * 0.35)))
    sns.heatmap(pivot, cmap="YlOrRd", linewidths=0.3, cbar_kws={"label": "Periodic IoC"})
    plt.title("Friedman Scan: Periodic IoC by Candidate Key Length", fontsize=14)
    plt.xlabel("Candidate Key Length")
    plt.ylabel("Page")
    plt.tight_layout()
    out = csv_file.replace(".csv", "_heatmap.png")
    plt.savefig(out, dpi=250, bbox_inches="tight")
    plt.close()
    print(f"Friedman scan heatmap saved: {out}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_cluster_mutual_ioc — cluster_mutual_ioc.csv  ← NEW
# ---------------------------------------------------------------------------

def plot_cluster_mutual_ioc(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    edges = pd.read_csv(csv_file)

    pages = sorted(
        set(edges["PageA"]).union(edges["PageB"])
    )

    matrix = pd.DataFrame(
        np.nan,
        index=pages,
        columns=pages
    )

    for _, row in edges.iterrows():
        a = row["PageA"]
        b = row["PageB"]
        v = row["AvgMutualIoC"]

        matrix.loc[a, b] = v
        matrix.loc[b, a] = v

    np.fill_diagonal(matrix.values, 1.0)

    plt.figure(figsize=(12, 10))
    sns.heatmap(
        matrix,
        cmap="Blues",
        annot=True,
        fmt=".3f",
        linewidths=0.4
    )

    plt.title("Mutual IoC between Cluster Pages")
    plt.tight_layout()

    out = csv_file.replace(".csv", "_heatmap.png")
    plt.savefig(out, dpi=250, bbox_inches="tight")
    plt.close()

    print(f"Cluster Mutual IoC heatmap saved: {out}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_rolling_ioc_from_log — rolling_ioc_analysis.txt
# ---------------------------------------------------------------------------

def plot_rolling_ioc_from_csv(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        print(f"No data found in {csv_file}")
        return

    # Change-point detection (PELT) if ruptures available
    rupture_results = []
    if rpt:
        print("\n--- STRUCTURAL CHANGE DETECTION (IoC Change Points) ---")
        for page, grp in df.groupby("Page"):
            if len(grp) > 15:
                try:
                    signal = grp["IoC"].values
                    algo   = rpt.Pelt(model="rbf").fit(signal)
                    breaks = algo.predict(pen=10)
                    if len(breaks) > 1:
                        print(f"  [{page}] Possible change points: {breaks}")
                    rupture_results.append({"Page": page, "Breaks": breaks[:-1]})
                except Exception:
                    pass
        pd.DataFrame(rupture_results).to_csv(
            os.path.join(os.path.dirname(csv_file), "ioc_ruptures.csv"), index=False
        )

    out_dir = os.path.join(os.path.dirname(csv_file) or ".", "rolling_plots")
    os.makedirs(out_dir, exist_ok=True)

    for page, grp in df.groupby("Page"):
        grp = grp.sort_values("Position")
        plt.figure(figsize=(15, 5))
        plt.plot(grp["Position"], grp["IoC"], marker="o", linestyle="-", markersize=2, color="crimson", linewidth=1)
        plt.axhline(y=0.03448, color="gray",  linestyle="--", label="Random (1/29 ≈ 0.034)")
        plt.axhline(y=0.0667, color="green", linestyle="--", label="Target (Liber ≈ 0.067)")
        plt.fill_between(grp["Position"], grp["IoC"], color="crimson", alpha=0.1)
        plt.title(f"Rolling IoC Metrics: {page}", fontsize=14)
        plt.xlabel("Window position (starting rune)")
        plt.ylabel("Index of Coincidence")
        plt.legend(loc="upper right")
        plt.ylim(0.0, 0.15) # Zoom out to see references with more perspective
        plt.grid(True, alpha=0.3)
        # Filename sanitization to avoid issues with special characters
        clean_name = re.sub(r'[^\w\-_\.]', '_', page)
        plt.savefig(
            os.path.join(out_dir, f"ioc_{clean_name}.png"), dpi=150, bbox_inches="tight"
        )
        plt.close()

    print(f"Rolling IoC plots saved in: {out_dir}")
    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_kasiski — kasiski_results.txt
# ---------------------------------------------------------------------------

def plot_kasiski_summary(txt_file: str, cache: dict) -> None:
    """Extract GCDs from a Kasiski results file and plot the distribution."""
    if not needs_processing(txt_file, cache):
        return
    if not os.path.exists(txt_file):
        return

    gcds: list = []
    with open(txt_file, "r", encoding="utf-8") as f:
        for line in f:
            m = re.search(r"GCD of deltas:\s*(\d+)", line)
            if m:
                gcd_val = int(m.group(1))
                if gcd_val > 1:
                    gcds.append(gcd_val)

    if not gcds:
        print(f"No GCDs extracted from {txt_file}")
        mark_processed(txt_file, cache)
        return

    from collections import Counter
    gcd_counts = Counter(gcds)
    labels, values = zip(*sorted(gcd_counts.items()))

    plt.figure(figsize=(12, 5))
    plt.bar([str(l) for l in labels], values, color="#4e79a7")
    plt.xlabel("GCD of Deltas")
    plt.ylabel("Occurrences")
    plt.title("Kasiski: Distribution of GCDs (candidate key lengths)")
    plt.tight_layout()
    out = txt_file.replace(".txt", "_gcd_dist.png")
    plt.savefig(out, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Kasiski GCD plot saved: {out}")

    mark_processed(txt_file, cache)

# ---------------------------------------------------------------------------
# plot_entropy_vs_ioc — heuristic_scores.csv + analysis.txt
# ---------------------------------------------------------------------------

def plot_entropy_vs_ioc(heuristic_csv: str, analysis_txt: str, cache: dict) -> None:
    key = f"{heuristic_csv}|{analysis_txt}"
    # Cache based on the two input files
    h_changed   = needs_processing(heuristic_csv, cache)
    txt_changed  = needs_processing(analysis_txt, cache)
    if not h_changed and not txt_changed:
        print(f"[CACHE HIT] entropy_vs_ioc — no input files changed, skipping.")
        return

    if not os.path.exists(heuristic_csv) or not os.path.exists(analysis_txt):
        return

    h_df        = pd.read_csv(heuristic_csv)
    entropy_data: dict = {}
    with open(analysis_txt, "r", encoding="utf-8") as f:
        current_page = None
        for line in f:
            if line.startswith("Page: "):
                current_page = line.split(": ")[1].split(" (")[0].strip()
            elif "Entropy:" in line and current_page:
                m = re.search(r"Entropy:\s+([\d.]+)", line)
                if m:
                    entropy_data[current_page] = float(m.group(1))

    h_df["Entropy"] = h_df["Page"].map(entropy_data)
    h_df = h_df.dropna(subset=["Entropy"])
    if h_df.empty:
        return

    plt.figure(figsize=(10, 8))
    scatter = plt.scatter(
        h_df["IoC"], h_df["Entropy"],
        c=h_df["Fitness"], cmap="viridis", s=100, alpha=0.7,
    )
    plt.colorbar(scatter, label="Fitness Score")
    plt.axvline(x=0.034, color="r", linestyle="--", alpha=0.3, label="Random IoC")
    plt.axvline(x=0.067, color="g", linestyle="--", alpha=0.3, label="Plaintext IoC")
    for i, txt in enumerate(h_df["Page"]):
        plt.annotate(txt, (h_df["IoC"].iloc[i], h_df["Entropy"].iloc[i]), fontsize=8, alpha=0.8)
    plt.title("Crypto-Signature: Entropy vs Index of Coincidence", fontsize=14)
    plt.xlabel("Index of Coincidence (IoC)")
    plt.ylabel("Entropy (Bits per Rune)")
    plt.grid(True, alpha=0.2)
    out = heuristic_csv.replace(".csv", "_entropy_ioc.png")
    plt.savefig(out, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Plot Entropy vs IoC saved: {out}")

    mark_processed(heuristic_csv, cache)
    mark_processed(analysis_txt, cache)

# ---------------------------------------------------------------------------
# plot_zipf_law_analysis — liber_unigram_target.csv
# ---------------------------------------------------------------------------

def plot_zipf_law_analysis(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df    = pd.read_csv(csv_file)
    freqs = sorted(df["Frequency"].values, reverse=True)
    ranks = np.arange(1, len(freqs) + 1)

    plt.figure(figsize=(8, 6))
    plt.loglog(ranks, freqs, marker="o", linestyle="none", label="Liber Primus Distribution")
    plt.loglog(ranks, freqs[0] / ranks, linestyle="--", color="gray", alpha=0.5, label="Ideal Zipf (s=1)")
    plt.title("Zipf Analysis (Resolved Pages)", fontsize=14)
    plt.xlabel("Rank (Log)")
    plt.ylabel("Frequency (Log)")
    plt.legend()
    plt.grid(True, which="both", ls="-", alpha=0.1)
    out = csv_file.replace(".csv", "_zipf.png")
    plt.savefig(out, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Zipf analysis saved: {out}")

    # Do not call mark_processed here as plot_unigram_distribution already does/will do it

# ---------------------------------------------------------------------------
# plot_delta_autocorrelation — delta_autocorrelation.csv (NOVO)
# ---------------------------------------------------------------------------

def plot_delta_autocorrelation(csv_file: str, cache: dict) -> None:
    """Generate line plots for delta autocorrelation (search for periodicity)."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    out_dir = os.path.join(os.path.dirname(csv_file), "delta_autocorr_plots")
    os.makedirs(out_dir, exist_ok=True)

    for page_name, grp in df.groupby("Page"):
        plt.figure(figsize=(14, 4))
        plt.plot(grp["Lag"], grp["Score"], marker='o', markersize=3, linestyle='-', color='indigo')
        
        # Highlight multiples of 29 (rune alphabet size)
        max_lag = grp["Lag"].max()
        for mult in range(29, max_lag + 1, 29):
            plt.axvline(x=mult, color="orange", linestyle="--", alpha=0.5)
            
        # Highlight lag with highest score (ignoring lag 1 and 2 which are usually doublet noise)
        valid_lags = grp[grp["Lag"] > 2]
        if not valid_lags.empty:
            best_lag = valid_lags.loc[valid_lags["Score"].idxmax()]
            if best_lag["Score"] > 0.05: # Sensitive threshold
                plt.axvline(x=best_lag["Lag"], color="red", linestyle=":", alpha=0.8, 
                            label=f"Peak: Lag {int(best_lag['Lag'])} (Score: {best_lag['Score']:.3f})")
                plt.legend()

        plt.title(f"Delta Autocorrelation (Crypto-Periodicity): {page_name}", fontsize=13)
        plt.xlabel("Lag (shift)")
        plt.ylabel("Score (match rate)")
        plt.grid(True, alpha=0.3)
        
        clean = str(page_name).replace(" ", "_")
        out = os.path.join(out_dir, f"delta_autocorr_{clean}.png")
        plt.savefig(out, dpi=150, bbox_inches="tight")
        plt.close()

    print(f"Delta autocorrelation plots saved in: {out_dir}")
    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_delta_stream_dist — delta_stream_analysis.csv (NOVO)
# ---------------------------------------------------------------------------

def plot_delta_stream_dist(csv_file: str, cache: dict) -> None:
    """Generate histograms for the frequency of Delta Stream values (0-28)."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    # Global Delta Histogram
    plt.figure(figsize=(10, 5))
    sns.countplot(data=df, x="Delta", hue="Delta", palette="viridis", legend=False)
    plt.title("Global Distribution of Delta Stream Values (0-28)", fontsize=14)
    plt.xlabel("Delta value (C[i] - C[i-1])")
    plt.ylabel("Frequency")
    
    out_global = csv_file.replace(".csv", "_global_dist.png")
    plt.savefig(out_global, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Global delta stream distribution saved: {out_global}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_secrets_analysis — cuneiform_stream.csv & secrets_matrices.csv (NOVO)
# ---------------------------------------------------------------------------

def plot_secrets_analysis(output_dir: str, cache: dict) -> None:
    cun_path = os.path.join(output_dir, "cuneiform_stream.csv")
    mat_path = os.path.join(output_dir, "secrets_matrices.csv")

    # Plot Cuneiform Stream
    if os.path.exists(cun_path) and needs_processing(cun_path, cache):
        df = pd.read_csv(cun_path)
        plt.figure(figsize=(15, 5))
        plt.plot(df["Index"], df["Decimal"], color="darkgreen", marker=".", markersize=4, alpha=0.6)
        plt.title("Cuneiform Stream (Base60 to Decimal)", fontsize=14)
        plt.xlabel("Index")
        plt.ylabel("Value")
        plt.grid(True, alpha=0.3)
        out_img = cun_path.replace(".csv", "_plot.png")
        plt.savefig(out_img, dpi=200, bbox_inches="tight")
        plt.close()
        mark_processed(cun_path, cache)

    # Plot Matrices as Heatmaps
    if os.path.exists(mat_path) and needs_processing(mat_path, cache):
        df_mat = pd.read_csv(mat_path)
        for m_id in df_mat["MatrixID"].unique():
            subset = df_mat[df_mat["MatrixID"] == m_id]
            pivot = subset.pivot(index="Row", columns="Col", values="Value")
            plt.figure(figsize=(6, 5))
            sns.heatmap(pivot, annot=True, fmt="d", cmap="YlGnBu", cbar=False)
            plt.title(f"Secret Matrix #{m_id}", fontsize=12)
            plt.savefig(os.path.join(output_dir, f"secret_matrix_{m_id}.png"), dpi=150)
            plt.close()
        mark_processed(mat_path, cache)

    # Plot Hash Nibble Distribution
    hash_path = os.path.join(output_dir, "deep_hash_distribution.csv")
    if os.path.exists(hash_path) and needs_processing(hash_path, cache):
        df_h = pd.read_csv(hash_path)
        plt.figure(figsize=(10, 4))
        sns.barplot(data=df_h, x="Nibble", y="Count", hue="Nibble", palette="viridis", legend=False)
        plt.title("Nibble Distribution of DEEP_HASH", fontsize=12)
        plt.savefig(os.path.join(output_dir, "deep_hash_plot.png"), dpi=150)
        plt.close()
        mark_processed(hash_path, cache)

# ---------------------------------------------------------------------------
# generate_master_summary — todos os .txt
# ---------------------------------------------------------------------------

def generate_master_summary(output_dir: str, cache: dict) -> None:
    txt_files    = glob.glob(os.path.join(output_dir, "*.txt"))
    summary_path = os.path.join(output_dir, "MASTER_RESEARCH_SUMMARY.log")
    keywords     = ["HIT", "Anomaly", "[!]", "STRONG", "Cluster found", "Pattern [", "KeyLen", "Fitness=0.9", "GCD", "Cluster #"]

    # Check if any txt changed before regenerating
    any_changed = any(needs_processing(p, cache) for p in txt_files)
    if not any_changed:
        print("[CACHE HIT] MASTER_RESEARCH_SUMMARY - no .txt changed, skipping.")
        return

    print(f"Generating master summary at {summary_path}...")
    with open(summary_path, "w", encoding="utf-8") as master:
        master.write("=== CICADA 3301 RESEARCH: MASTER ANALYTICAL SUMMARY ===\n")
        master.write(f"Generation date: {pd.Timestamp.now()}\n\n")

        for f_path in txt_files:
            fname = os.path.basename(f_path)
            if "MASTER_RESEARCH_SUMMARY" in fname:
                continue
            master.write(f"\n>>> FILE: {fname}\n")
            try:
                with open(f_path, "r", encoding="utf-8") as f:
                    lines = f.readlines()

                if "_report.txt" in fname:
                    master.write("--- Correlation Report Summary ---\n")
                    report_keywords = [
                        "Overall Mean Correlation:",
                        "Modularity (Louvain):",
                        "--- TOP 20 STRONGEST CORRELATIONS ---",
                        "--- HUB PAGES",
                        "--- STATISTICAL OUTLIERS",
                        "--- PAGES FAR FROM PCA CENTER",
                        "=== TOP SUSPICIOUS PAGES",
                        "High Correlation Density",
                    ]
                    report_content = []
                    capture_lines = False
                    for line in lines:
                        if any(k in line for k in report_keywords):
                            capture_lines = True
                            report_content.append(line.strip())
                        elif capture_lines and (line.strip() == "" or line.strip().startswith("---") or line.strip().startswith("===")):
                            capture_lines = False
                        elif capture_lines:
                            report_content.append(line.strip())
                    
                    if report_content:
                        for rl in report_content:
                            master.write(f"  [REPORT] {rl}\n")
                    elif any(k in "".join(lines) for k in keywords):
                        master.write("No key insights extracted from report.\n")
                else:
                    # Captura a linha de contexto caso encontre um hit
                    relevant = []
                    for i, line in enumerate(lines):
                        if any(k in line for k in keywords):
                            relevant.append(line.strip())
                    
                    if relevant:
                        master.write(f"Total points of interest: {len(relevant)}\n")
                        for rl in relevant[:15]:
                            master.write(f"  [LOG] {rl}\n")
                        if len(relevant) > 15:
                            master.write(f"  ... and {len(relevant)-15} more entries.\n")
                    else:
                        master.write("No immediate critical patterns detected.\n")
            except Exception as exc:
                master.write(f"Error reading file: {exc}\n")

    # Register all txts as processed
    for p in txt_files:
        if os.path.exists(p):
            mark_processed(p, cache)

if __name__ == "__main__":
    OUTPUT_DIR = "../output"
    if not os.path.exists(OUTPUT_DIR):
        print(f"Folder {OUTPUT_DIR} not found. Run the C++ code first.")
        exit(1)

    # Load hash cache from disk
    cache = _load_cache()

    print("Starting full data scan (with SHA-256 cache)...\n")

    # --- Correlation CSVs ---
    for csv_path in glob.glob(os.path.join(OUTPUT_DIR, "corr_*.csv")):
        plot_correlation_matrix(csv_path, cache)

    # --- Interruption Deltas ---
    for csv_path in glob.glob(os.path.join(OUTPUT_DIR, "interrupt_deltas*.csv")):
        plot_delta_histograms(csv_path, cache)

    # --- Target Unigram Distribution ---
    unigram_csv = os.path.join(OUTPUT_DIR, "liber_unigram_target.csv")
    plot_unigram_distribution(unigram_csv, cache)
    plot_zipf_law_analysis(unigram_csv, cache)

    # --- Cipher Heuristics ---
    heuristic_csv = os.path.join(OUTPUT_DIR, "heuristic_scores.csv")
    plot_heuristic_summary(heuristic_csv, cache)

    # --- Key Stream ---
    ks_csv = os.path.join(OUTPUT_DIR, "key_stream_analysis.csv")
    plot_key_stream_analysis(ks_csv, cache)

    # --- Page Features (new) ---
    feat_csv = os.path.join(OUTPUT_DIR, "page_features.csv")
    plot_page_features(feat_csv, cache)

    # --- Friedman Scan (new) ---
    friedman_csv = os.path.join(OUTPUT_DIR, "friedman_scan.csv")
    plot_friedman_scan(friedman_csv, cache)

    # --- Cluster Mutual IoC (new) ---
    cluster_csv = os.path.join(OUTPUT_DIR, "cluster_mutual_ioc.csv")
    plot_cluster_mutual_ioc(cluster_csv, cache)

    # --- Rolling IoC (Full data CSV) ---
    rolling_ioc_csv = os.path.join(OUTPUT_DIR, "rolling_ioc_peaks.csv")
    plot_rolling_ioc_from_csv(rolling_ioc_csv, cache)

    # --- Kasiski (text log, new) ---
    kasiski_txt = os.path.join(OUTPUT_DIR, "kasiski_results.txt")
    plot_kasiski_summary(kasiski_txt, cache)

    # --- Entropy vs Cross IoC ---
    analysis_txt = os.path.join(OUTPUT_DIR, "analysis.txt")
    plot_entropy_vs_ioc(heuristic_csv, analysis_txt, cache)

    # --- Delta Stream and Autocorrelation (NEW) ---
    delta_stream_csv = os.path.join(OUTPUT_DIR, "delta_stream_analysis.csv")
    plot_delta_stream_dist(delta_stream_csv, cache)

    delta_autocorr_csv = os.path.join(OUTPUT_DIR, "delta_autocorrelation.csv")
    plot_delta_autocorrelation(delta_autocorr_csv, cache)

    # --- Gematria Analysis (NEW) ---
    gematria_csv = os.path.join(OUTPUT_DIR, "gematria_sums.csv")
    plot_gematria_analysis(gematria_csv, cache)
    
    plot_secrets_analysis(OUTPUT_DIR, cache)

    # --- Master analytical summary of all .txt ---
    generate_master_summary(OUTPUT_DIR, cache)

    run_doublet_analysis_pipeline(cache)

    # Persist updated cache to disk
    _save_cache(cache)

    print("\n[SUCCESS] All files have been processed. Cache updated on", CACHE_FILE)