"""
visualize_correlations.py — Cicada 3301 / Liber Primus
Full scan of all CSV/TXT files generated by the C++ tools with SHA-256 hash caching.
If the file size in bytes and the SHA-256 haven't changed since the last run,
that file's analysis is automatically skipped.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import re
import json
import hashlib
import glob

from sklearn.decomposition import PCA
import numpy as np
import networkx as nx
from scipy.stats import zscore
from scipy.spatial.distance import pdist, squareform
from networkx.algorithms.community import louvain_communities, modularity

try:
    import ruptures as rpt
except ImportError:
    rpt = None

# ---------------------------------------------------------------------------
# SHA-256 Hash Cache System
# ---------------------------------------------------------------------------

CACHE_DIR  = "../output/.cache"
CACHE_FILE = os.path.join(CACHE_DIR, "file_hashes.json")

def _load_cache() -> dict:
    """Load the JSON of persisted file hashes from disk."""
    os.makedirs(CACHE_DIR, exist_ok=True)
    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}
    return {}

def _save_cache(cache: dict) -> None:
    """Persist the JSON of file hashes to disk."""
    os.makedirs(CACHE_DIR, exist_ok=True)
    with open(CACHE_FILE, "w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2)

def _file_fingerprint(path: str) -> dict:
    """Return file size in bytes and SHA-256 hex of a file."""
    size = os.path.getsize(path)
    sha  = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            sha.update(chunk)
    return {"size": size, "sha256": sha.hexdigest()}

def needs_processing(path: str, cache: dict) -> bool:
    """
    Return True if the file needs (re)processing.
    Return False if size and SHA-256 match the previous record.
    """
    if not os.path.exists(path):
        return False
    fp = _file_fingerprint(path)
    prev = cache.get(os.path.abspath(path))
    if prev and prev.get("size") == fp["size"] and prev.get("sha256") == fp["sha256"]:
        print(f"[CACHE HIT] {os.path.basename(path)} - unchanged, skipping.")
        return False
    return True

def mark_processed(path: str, cache: dict) -> None:
    """Record the current fingerprint of the file in the cache."""
    if os.path.exists(path):
        cache[os.path.abspath(path)] = _file_fingerprint(path)

# ---------------------------------------------------------------------------
# Math helpers
# ---------------------------------------------------------------------------

def is_prime(n: int) -> bool:
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

def get_fibonacci(max_val: int) -> list:
    fibs = [1, 2]
    while fibs[-1] < max_val:
        fibs.append(fibs[-1] + fibs[-2])
    return fibs

def find_repeating_sequences(deltas: list, n: int = 3) -> dict:
    """Search for repeating n-grams of deltas."""
    sequences: dict = {}
    for i in range(len(deltas) - n + 1):
        seq = tuple(deltas[i : i + n])
        sequences[seq] = sequences.get(seq, 0) + 1
    return {k: v for k, v in sequences.items() if v > 1}

# ---------------------------------------------------------------------------
# Generate textual report with suspicion score
# ---------------------------------------------------------------------------

def generate_textual_report(df, csv_file: str, principal_components=None) -> None:
    report_file = csv_file.replace(".csv", "_report.txt")

    G = nx.from_pandas_adjacency(df)
    mask = np.ones(df.shape, dtype=bool)
    np.fill_diagonal(mask, 0)

    corr_pairs = df.where(mask).stack().reset_index()
    corr_pairs.columns = ["Page_A", "Page_B", "Correlation"]
    top_corrs  = corr_pairs.sort_values("Correlation", ascending=False).head(20)
    all_values = corr_pairs["Correlation"].values
    page_means = df.where(mask).mean()

    degree_cent  = nx.degree_centrality(G)
    betweenness  = nx.betweenness_centrality(G)
    communities  = louvain_communities(G, weight="weight", resolution=1, seed=42)
    mod          = modularity(G, communities, weight="weight")
    z_scores_corr = zscore(page_means)
    z_series     = pd.Series(z_scores_corr, index=page_means.index)

    features_path = os.path.join(os.path.dirname(csv_file), "page_features.csv")
    features_df   = None
    if os.path.exists(features_path):
        features_df = pd.read_csv(features_path, index_col=0)

    outliers = z_series[z_series < -2]

    with open(report_file, "w", encoding="utf-8") as f:
        f.write(f"=== ADVANCED STATISTICAL REPORT: {os.path.basename(csv_file)} ===\n\n")
        f.write(f"Overall Mean Correlation: {np.mean(all_values):.4f}\n")
        f.write(f"Modularity (Louvain): {mod:.4f} ")
        if   mod < 0.2: f.write("(Weak Structure)\n")
        elif mod < 0.4: f.write("(Moderate Structure)\n")
        else:           f.write("(Strong Clusters)\n")
        f.write(f"Median: {np.median(all_values):.4f}\n")
        f.write(f"Std Dev: {np.std(all_values):.4f}\n")
        f.write(f"Variance: {np.var(all_values):.4f}\n")
        f.write(f"Max Value (excl. diagonal): {np.max(all_values):.4f}\n")
        f.write(f"Min Value: {np.min(all_values):.4f}\n\n")

        f.write("--- TOP 20 STRONGEST CORRELATIONS ---\n")
        for _, row in top_corrs.iterrows():
            f.write(f"{row['Page_A']} <-> {row['Page_B']}: {row['Correlation']:.6f}\n")

        f.write("\n--- NETWORK CENTRALITY (Bridge/Transit Pages) ---\n")
        for page in sorted(degree_cent, key=degree_cent.get, reverse=True)[:10]:
            f.write(f"{page:10}: Degree={degree_cent[page]:.4f} Betweenness={betweenness[page]:.4f}\n")

        f.write("\n--- DETECTED COMMUNITIES (Louvain) ---\n")
        for i, c in enumerate(communities):
            f.write(f"Cluster {i+1}: {len(c)} páginas ({', '.join(list(c)[:5])}...)\n")

        f.write("\n--- HUB PAGES (High mean similarity with the book) ---\n")
        hub_pages = df.where(mask).mean().sort_values(ascending=False).head(5)
        for page, val in hub_pages.items():
            f.write(f"{page}: Correlação média {val:.4f}\n")

        f.write("\n--- STATISTICAL OUTLIERS (Z-Score < -2) ---\n")
        if outliers.empty:
            f.write("No statistical outliers detected.\n")
        else:
            for page, val in outliers.items():
                f.write(f"{page}: Z={val:.2f}\n")

        z_pca_scores: dict = {}
        if principal_components is not None:
            dist_pca = np.sqrt(
                principal_components[:, 0] ** 2 + principal_components[:, 1] ** 2
            )
            idx_ext = np.argsort(dist_pca)[::-1][:10]
            f.write("\n--- PAGES FAR FROM PCA CENTER (Language anomalies) ---\n")
            for i in idx_ext:
                f.write(f"{df.index[i]:10}: Distância {dist_pca[i]:.3f}\n")
            z_pca_vals = zscore(dist_pca)
            for i, name in enumerate(df.index):
                z_pca_scores[name] = z_pca_vals[i]

        f.write("\n=== TOP SUSPICIOUS PAGES (PRIORITY SCORE) ===\n")
        heuristic_path = os.path.join(os.path.dirname(csv_file), "heuristic_scores.csv")
        h_df = pd.read_csv(heuristic_path, index_col=0) if os.path.exists(heuristic_path) else None

        suspicion_list = []
        for name in df.index:
            z_corr = abs(z_series[name])
            z_pca  = abs(z_pca_scores.get(name, 0))
            cent   = betweenness.get(name, 0)
            score  = (z_corr * 0.2) + (z_pca * 0.4) + (cent * 5.0)

            if features_df is not None and name in features_df.index:
                f_row    = features_df.loc[name]
                ioc_dev  = abs(f_row.get("IoC",     0.034) - 0.067)
                ent_dev  = abs(f_row.get("Entropy", 4.3)   - 4.25)   # noqa: F841
                lrs_bonus = f_row.get("LRS", 0) * 0.5
                score = 0.2 * z_corr + 0.2 * z_pca + 0.3 * ioc_dev + 0.2 * cent + lrs_bonus

            suspicion_list.append((name, score))

        suspicion_list.sort(key=lambda x: x[1], reverse=True)
        for name, score in suspicion_list[:15]:
            f.write(f"{name:12} -> Score: {score:.2f}\n")

        f.write("\n--- INTERNAL STRUCTURE ANALYSIS ---\n")
        high_corr_threshold = 0.8
        dense_count = np.sum(all_values > high_corr_threshold)
        density = dense_count / len(all_values)
        f.write(f"High Correlation Density (>0.8): {density * 100:.2f}%\n")
        f.write(
            "Note: A high density suggests that a large portion of the book "
            "shares the same ciphering algorithm.\n"
        )

    print(f"Textual report saved: {report_file}")

# ---------------------------------------------------------------------------
# plot_correlation_matrix — heatmap + clustermap + network + PCA
# ---------------------------------------------------------------------------

def plot_correlation_matrix(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return

    if not os.path.exists(csv_file):
        print(f"File not found: {csv_file}")
        return

    df = pd.read_csv(csv_file, index_col=0)
    principal_components = None
    pca = None
    if df.shape[0] > 1:
        pca = PCA(n_components=2)
        principal_components = pca.fit_transform(df)

    generate_textual_report(df, csv_file, principal_components)

    # Matriz de distância cosseno
    dist_mat = squareform(pdist(df.values, metric="cosine"))
    plt.figure(figsize=(12, 10))
    sns.heatmap(dist_mat, cmap="viridis", center=None, square=True)
    plt.title(f"Distance Matrix (Cosine): {os.path.basename(csv_file)}")
    plt.savefig(csv_file.replace(".csv", "_dist_cosine.png"), dpi=300, bbox_inches="tight")
    plt.close()

    sns.set_theme(style="white")

    # Heatmap simples
    plt.figure(figsize=(14, 12))
    sns.heatmap(
        df, cmap="RdYlBu_r", center=0, square=True,
        linewidths=0.5, cbar_kws={"shrink": 0.8},
    )
    plt.title(f"Correlation Matrix: {csv_file}", fontsize=16)
    plt.savefig(csv_file.replace(".csv", "_heatmap.png"), dpi=300, bbox_inches="tight")
    print(f"Heatmap saved: {csv_file.replace('.csv','_heatmap.png')}")
    plt.close()

    # Clustermap hierárquico
    cg = sns.clustermap(  # noqa: F841
        df, cmap="RdYlBu_r", center=0, method="ward", figsize=(15, 15), linewidths=0.5
    )
    plt.title(f"Hierarchical Clustering: {csv_file}", fontsize=16, pad=100)
    plt.savefig(csv_file.replace(".csv", "_cluster.png"), dpi=300, bbox_inches="tight")
    print(f"Clustermap saved: {csv_file.replace('.csv','_cluster.png')}")
    plt.close()

    # Network graph (threshold adaptativo)
    try:
        G = nx.Graph()
        mask_net = np.ones(df.shape, dtype=bool)
        np.fill_diagonal(mask_net, 0)
        all_corr_vals = df.where(mask_net).stack().values
        threshold = float(np.mean(all_corr_vals) + 1.5 * np.std(all_corr_vals))
        threshold = max(0.7, min(threshold, 0.98))

        for i in range(len(df.index)):
            for j in range(i + 1, len(df.columns)):
                if df.iloc[i, j] > threshold:
                    G.add_edge(df.index[i], df.columns[j], weight=df.iloc[i, j])

        if len(G.nodes) > 0:
            plt.figure(figsize=(12, 12))
            pos     = nx.spring_layout(G, k=0.5, iterations=50)
            edges   = G.edges()
            weights = [G[u][v]["weight"] * 2 for u, v in edges]
            nx.draw_networkx_nodes(G, pos, node_size=700, node_color="skyblue", alpha=0.8)
            nx.draw_networkx_edges(G, pos, edgelist=edges, width=weights, edge_color="gray", alpha=0.5)
            nx.draw_networkx_labels(G, pos, font_size=10, font_family="sans-serif")
            plt.title(f"Network of Highly Correlated Pages (>{threshold:.2f})", fontsize=14)
            plt.savefig(csv_file.replace(".csv", "_network.png"), dpi=300, bbox_inches="tight")
            plt.close()
            print(f"Network graph saved: {csv_file.replace('.csv','_network.png')}")
    except Exception as exc:
        print(f"Error generating network graph: {exc}")

    # PCA scatter
    if pca is not None and principal_components is not None:
        try:
            pca_df = pd.DataFrame(
                principal_components,
                columns=["principal_component_1", "principal_component_2"],
            )
            pca_df["Page"] = df.index
            plt.figure(figsize=(12, 10))
            sns.scatterplot(
                x="principal_component_1", y="principal_component_2",
                hue="Page", data=pca_df, s=100,
            )
            plt.title(f"Correlation PCA: {csv_file}", fontsize=16)
            plt.xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.2f}%)")
            plt.ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.2f}%)")
            for _, row in pca_df.iterrows():
                plt.text(
                    row["principal_component_1"] + 0.01,
                    row["principal_component_2"] + 0.01,
                    row["Page"], fontsize=8, ha="left", va="bottom",
                )
            plt.savefig(csv_file.replace(".csv", "_pca.png"), dpi=300, bbox_inches="tight")
            print(f"PCA plot saved: {csv_file.replace('.csv','_pca.png')}")
            plt.close()
        except Exception as exc:
            print(f"Error generating PCA for {csv_file}: {exc}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_delta_histograms — interrupt_deltas.csv
# ---------------------------------------------------------------------------

def plot_delta_histograms(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    print(f"\n{'='*60}")
    print(f"--- DEEP DELTA ANALYSIS: {os.path.basename(csv_file)} ---")
    print("=" * 60)

    all_deltas = df["Delta"].tolist()
    max_d      = int(df["Delta"].max())
    fibs       = get_fibonacci(max_d)
    top_deltas = df["Delta"].value_counts().head(10)

    print("\n[1. Mathematical properties of top deltas]")
    for delta, count in top_deltas.items():
        d_int      = int(delta)
        percentage = (count / len(df)) * 100
        props      = []
        if d_int in fibs:     props.append("FIBONACCI")
        if is_prime(d_int):   props.append("PRIME")
        prop_str = f"({', '.join(props)})" if props else ""
        print(f"  Delta {d_int:3d}: {count:3d} times ({percentage:5.2f}%) {prop_str}")

    print("\n[2. Cycle detection (repeating sequences)]")
    for n in range(3, 6):
        repeats = find_repeating_sequences(all_deltas, n)
        if repeats:
            sorted_repeats = sorted(repeats.items(), key=lambda x: x[1], reverse=True)[:5]
            print(f"  Top {n}-grams:")
            for seq, count in sorted_repeats:
                print(f"    {list(seq)} -> {count} occurrences")

    print("\n[3. Suggestion for Skip-Vigenere attack]")
    if len(top_deltas) >= 3:
        suggested = [int(d) for d in top_deltas.index[:5]]
        print(f"  Try using this jump sequence: {suggested}")

    # Histograma por página (se coluna Page existir)
    if "Page" in df.columns:
        for page_name, grp in df.groupby("Page"):
            plt.figure(figsize=(10, 4))
            max_val = int(grp["Delta"].max())
            sns.histplot(data=grp, x="Delta", bins=range(0, max_val + 2), kde=False, color="teal")
            plt.title(f"Deltas — {page_name}", fontsize=13)
            plt.xlabel("Delta")
            plt.ylabel("Occurrences")
            clean = str(page_name).replace(" ", "_")
            out   = csv_file.replace(".csv", f"_hist_{clean}.png")
            plt.savefig(out, dpi=200, bbox_inches="tight")
            plt.close()

    # Histograma global
    plt.figure(figsize=(12, 6))
    sns.histplot(data=df, x="Delta", bins=range(0, max_d + 2), kde=False, color="teal")
    plt.title("Delta Frequency Distribution (Skip Intervals)", fontsize=14)
    plt.xlabel("Delta (distance between interrupts)")
    plt.ylabel("Occurrences")
    out_global = csv_file.replace(".csv", "_histogram.png")
    plt.savefig(out_global, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"\nHistogram saved: {out_global}")

    # TopDelta por página (se coluna TopDelta existir)
    if "TopDelta" in df.columns and "Page" in df.columns:
        top_df = df.sort_values("TopDelta", ascending=False).drop_duplicates("Page")
        plt.figure(figsize=(12, max(5, len(top_df) * 0.35)))
        plt.barh(top_df["Page"].astype(str), top_df["TopDelta"], color="#76b7b2")
        plt.xlabel("TopDelta (largest interval on page)")
        plt.title("Pages with largest interrupt intervals")
        plt.tight_layout()
        out_top = csv_file.replace(".csv", "_topdelta.png")
        plt.savefig(out_top, dpi=200, bbox_inches="tight")
        plt.close()
        print(f"TopDelta plot saved: {out_top}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_unigram_distribution — liber_unigram_target.csv
# ---------------------------------------------------------------------------

def plot_unigram_distribution(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    plt.figure(figsize=(12, 6))
    sns.barplot(
        x="RuneIndex", y="Frequency", data=df,
        hue="RuneIndex", palette="magma", legend=False,
    )
    plt.title("Target Unigram Frequency (based on resolved pages)", fontsize=14)
    plt.xlabel("Rune Index (0-28)")
    plt.ylabel("Relative Frequency")
    out = csv_file.replace(".csv", "_dist.png")
    plt.savefig(out, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Unigram distribution plot saved: {out}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_heuristic_summary — heuristic_scores.csv
# ---------------------------------------------------------------------------

def plot_heuristic_summary(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    df_sorted     = df.sort_values("Fitness", ascending=False)
    cipher_colors = {"None": "#aaaaaa", "Shift": "#4e79a7", "Atbash": "#f28e2b"}
    colors        = [cipher_colors.get(c, "#59a14f") for c in df_sorted["BestCipher"]]

    fig, axes = plt.subplots(1, 2, figsize=(18, max(6, len(df_sorted) * 0.35)))

    axes[0].barh(df_sorted["Page"], df_sorted["Fitness"], color=colors)
    axes[0].set_xlabel("Fitness Score (JSD)", fontsize=12)
    axes[0].set_title("Heuristic Ranking: Pages closest to solved", fontsize=13)
    axes[0].axvline(x=df_sorted["Fitness"].mean(),  color="red",    linestyle="--", alpha=0.6)
    axes[0].axvline(x=df_sorted["Fitness"].mean() + df_sorted["Fitness"].std(),
                    color="orange", linestyle=":",  alpha=0.6)
    from matplotlib.patches import Patch
    legend_elements = [Patch(facecolor=v, label=k) for k, v in cipher_colors.items()]
    axes[0].legend(handles=legend_elements, loc="lower right", fontsize=9)

    scatter_colors = [cipher_colors.get(c, "#59a14f") for c in df["BestCipher"]]
    axes[1].scatter(
        df["IoC"], df["Fitness"],
        c=scatter_colors, s=60, alpha=0.8, edgecolors="white", linewidth=0.5,
    )
    axes[1].axvline(x=0.034, color="gray",  linestyle="--", alpha=0.5, label="Random IoC (1/29)")
    axes[1].axvline(x=0.067, color="green", linestyle="--", alpha=0.5, label="IoC texto simples")
    axes[1].set_xlabel("Baseline IoC", fontsize=12)
    axes[1].set_ylabel("Fitness Score", fontsize=12)
    axes[1].set_title("IoC vs Fitness — Attack map", fontsize=13)
    for _, row in df.iterrows():
        axes[1].annotate(
            str(row["Page"]), (row["IoC"], row["Fitness"]),
            fontsize=7, alpha=0.7, xytext=(3, 3), textcoords="offset points",
        )
    axes[1].legend(fontsize=9)

    plt.tight_layout()
    out = csv_file.replace(".csv", "_dashboard.png")
    plt.savefig(out, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Heuristic dashboard saved: {out}")

    # Comprimentos de chave Vigenère
    if "BestVigenereKeyLen" in df.columns:
        vigenere_pages = df[df["BestVigenereKeyLen"] > 0].sort_values("BestVigenereKeyLen")
        if not vigenere_pages.empty:
            plt.figure(figsize=(10, max(4, len(vigenere_pages) * 0.4)))
            plt.barh(
                vigenere_pages["Page"].astype(str),
                vigenere_pages["BestVigenereKeyLen"],
                color="#76b7b2",
            )
            plt.xlabel("Estimated Vigenère key length", fontsize=12)
            plt.title("Pages with detected periodic pattern (possible Vigenère)", fontsize=13)
            plt.tight_layout()
            out_v = csv_file.replace(".csv", "_vigenere_keylens.png")
            plt.savefig(out_v, dpi=200, bbox_inches="tight")
            plt.close()
            print(f"Vigenère key lengths plot saved: {out_v}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_key_stream_analysis — key_stream_analysis.csv
# ---------------------------------------------------------------------------

def plot_key_stream_analysis(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    pages   = df["Page"].unique()
    n_pages = len(pages)
    if n_pages == 0:
        return

    max_pages_to_plot = 10 # Limita a 10 páginas por imagem para evitar DecompressionBombError
    pages_to_plot = pages[:max_pages_to_plot]
    
    if n_pages > max_pages_to_plot:
        print(f"Warning: Only plotting the first {max_pages_to_plot} of {n_pages} pages in key stream analysis to prevent image size issues.")

    fig, axes = plt.subplots(len(pages_to_plot), 2, figsize=(16, 4 * len(pages_to_plot)), squeeze=False)
    fig.suptitle("Análise da Key Stream (Páginas Resolvidas)", fontsize=15, y=1.01)

    # Itera apenas sobre as páginas selecionadas para plotar
    for i, page in enumerate(pages_to_plot):
        page_data = df[df["Page"] == page]
        # Filter out "UNRESOLVED" markers before converting to float
        numeric_series = page_data[page_data["KeyValue"] != "UNRESOLVED"]["KeyValue"]
        stream = numeric_series.values.astype(float)
        if len(stream) < 10:
            axes[i][0].set_title(f"{page} — stream muito curta")
            axes[i][1].set_title("")
            continue

        max_lag   = min(len(stream) // 2, 60)
        lags      = np.arange(1, max_lag + 1)
        autocorrs = []
        for lag in lags:
            s1, s2 = stream[:-lag], stream[lag:]
            if np.std(s1) == 0 or np.std(s2) == 0:
                autocorrs.append(0.0)
            else:
                autocorrs.append(np.corrcoef(s1, s2)[0, 1])

        conf = 1.96 / np.sqrt(len(stream))
        axes[i][0].bar(lags, autocorrs, color="steelblue", alpha=0.7)
        axes[i][0].axhline(y=0,     color="black", linewidth=0.8)
        axes[i][0].axhline(y= conf, color="red", linestyle="--", alpha=0.5, label=f"±95% ({conf:.3f})")
        axes[i][0].axhline(y=-conf, color="red", linestyle="--", alpha=0.5)
        axes[i][0].set_title(f"{page} — Autocorrelação da Key Stream", fontsize=11)
        axes[i][0].set_xlabel("Lag")
        axes[i][0].set_ylabel("Correlação")
        axes[i][0].legend(fontsize=8)

        fft_vals          = np.abs(np.fft.rfft(stream - stream.mean()))
        freqs             = np.fft.rfftfreq(len(stream))
        fft_vals[0]       = 0
        dominant_freq_idx = np.argmax(fft_vals[1:]) + 1
        dominant_period   = (
            int(round(1.0 / freqs[dominant_freq_idx])) if freqs[dominant_freq_idx] > 0 else 0
        )
        axes[i][1].plot(freqs[1:], fft_vals[1:], color="darkorange", linewidth=1)
        if dominant_freq_idx < len(freqs):
            axes[i][1].axvline(
                x=freqs[dominant_freq_idx], color="red", linestyle="--", alpha=0.7,
                label=f"Período dominante: {dominant_period}",
            )
        axes[i][1].set_title(f"{page} — FFT da Key Stream", fontsize=11)
        axes[i][1].set_xlabel("Frequência")
        axes[i][1].set_ylabel("Magnitude")
        axes[i][1].legend(fontsize=8)

    plt.tight_layout()
    out = csv_file.replace(".csv", "_fft_autocorr.png")
    plt.savefig(out, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"FFT/Autocorrelation analysis saved: {out}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_page_features — page_features.csv  ← NOVO: não existia antes
# ---------------------------------------------------------------------------

def plot_page_features(csv_file: str, cache: dict) -> None:
    """IoC vs Entropy scatter, Fitness ranking e métricas avançadas."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    # 1. Scatter IoC × Entropy colorido por Fitness
    plt.figure(figsize=(12, 8))
    sc = plt.scatter(
        df["IoC"], df["Entropy"],
        c=df["Fitness"], cmap="viridis", s=df["Length"] / df["Length"].max() * 300 + 40,
        alpha=0.8, edgecolors="white", linewidth=0.4,
    )
    plt.colorbar(sc, label="Fitness Score")
    plt.axvline(x=0.034, color="red",   linestyle="--", alpha=0.4, label="Random IoC")
    plt.axvline(x=0.067, color="green", linestyle="--", alpha=0.4, label="Plaintext IoC")
    for _, row in df.iterrows():
        plt.annotate(str(row["Page"]), (row["IoC"], row["Entropy"]), fontsize=7, alpha=0.8)
    plt.title("Cripto-Assinatura: Entropia vs Index of Coincidence", fontsize=14)
    plt.xlabel("Index of Coincidence (IoC)")
    plt.ylabel("Entropia (Bits por Runa)")
    plt.legend()
    plt.grid(True, alpha=0.2)
    out_scatter = csv_file.replace(".csv", "_entropy_ioc.png")
    plt.savefig(out_scatter, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Plot Entropia vs IoC salvo: {out_scatter}")

    # 2. Fitness ranking (barras)
    df_sorted = df.sort_values("Fitness", ascending=False)
    plt.figure(figsize=(14, max(6, len(df_sorted) * 0.35)))
    plt.barh(df_sorted["Page"].astype(str), df_sorted["Fitness"], color="#4e79a7")
    plt.xlabel("Advanced Fitness Score")
    plt.title("Ranking de Fitness por Página")
    plt.tight_layout()
    out_fit = csv_file.replace(".csv", "_fitness_ranking.png")
    plt.savefig(out_fit, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Fitness ranking salvo: {out_fit}")

    # 3. Chi-Square ranking
    if "ChiSquare" in df.columns:
        df_chi = df.sort_values("ChiSquare", ascending=False)
        plt.figure(figsize=(14, max(6, len(df_chi) * 0.35)))
        plt.barh(df_chi["Page"].astype(str), df_chi["ChiSquare"], color="#e15759")
        plt.xlabel("Chi-Square (distância da uniforme)")
        plt.title("Ranking Chi-Square por Página (maior = mais longe do ruído)")
        plt.tight_layout()
        out_chi = csv_file.replace(".csv", "_chi_ranking.png")
        plt.savefig(out_chi, dpi=200, bbox_inches="tight")
        plt.close()
        print(f"Chi-Square ranking salvo: {out_chi}")

    # 4. GPS Sum Mean
    if "GpsSumMean" in df.columns:
        df_gps = df.sort_values("GpsSumMean", ascending=False)
        plt.figure(figsize=(14, max(6, len(df_gps) * 0.35)))
        plt.barh(df_gps["Page"].astype(str), df_gps["GpsSumMean"], color="#76b7b2")
        plt.xlabel("GP Sum Mean (valor médio das palavras)")
        plt.title("GP Sum por Página")
        plt.tight_layout()
        out_gps = csv_file.replace(".csv", "_gps_mean.png")
        plt.savefig(out_gps, dpi=200, bbox_inches="tight")
        plt.close()
        print(f"GPS Sum ranking salvo: {out_gps}")

    # 5. BigramIoC
    if "BigramIoC" in df.columns:
        df_b = df.sort_values("BigramIoC", ascending=False)
        plt.figure(figsize=(14, max(6, len(df_b) * 0.35)))
        plt.barh(df_b["Page"].astype(str), df_b["BigramIoC"], color="#f1ce63")
        plt.xlabel("Bigram IoC")
        plt.title("Bigram Index of Coincidence por Página")
        plt.tight_layout()
        out_b = csv_file.replace(".csv", "_bigram_ioc.png")
        plt.savefig(out_b, dpi=200, bbox_inches="tight")
        plt.close()
        print(f"Bigram IoC ranking salvo: {out_b}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_friedman_scan — friedman_scan.csv  ← NOVO
# ---------------------------------------------------------------------------

def plot_friedman_scan(csv_file: str, cache: dict) -> None:
    """Heatmap of periodic IoC by page and candidate key length."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    # Espera colunas: Page, KeyLen, AvgColIoC
    if not {"Page", "KeyLen", "AvgColIoC"}.issubset(df.columns):
        print(f"friedman_scan.csv missing expected columns — skipping heatmap.")
        return

    pivot = df.pivot(index="Page", columns="KeyLen", values="AvgColIoC")
    plt.figure(figsize=(max(12, len(pivot.columns) * 0.6), max(8, len(pivot) * 0.35)))
    sns.heatmap(pivot, cmap="YlOrRd", linewidths=0.3, cbar_kws={"label": "Periodic IoC"})
    plt.title("Friedman Scan: Periodic IoC by Candidate Key Length", fontsize=14)
    plt.xlabel("Candidate Key Length")
    plt.ylabel("Page")
    plt.tight_layout()
    out = csv_file.replace(".csv", "_heatmap.png")
    plt.savefig(out, dpi=250, bbox_inches="tight")
    plt.close()
    print(f"Friedman scan heatmap saved: {out}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_cluster_mutual_ioc — cluster_mutual_ioc.csv  ← NOVO
# ---------------------------------------------------------------------------

def plot_cluster_mutual_ioc(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    edges = pd.read_csv(csv_file)

    pages = sorted(
        set(edges["PageA"]).union(edges["PageB"])
    )

    matrix = pd.DataFrame(
        np.nan,
        index=pages,
        columns=pages
    )

    for _, row in edges.iterrows():
        a = row["PageA"]
        b = row["PageB"]
        v = row["AvgMutualIoC"]

        matrix.loc[a, b] = v
        matrix.loc[b, a] = v

    np.fill_diagonal(matrix.values, 1.0)

    plt.figure(figsize=(12, 10))
    sns.heatmap(
        matrix,
        cmap="Blues",
        annot=True,
        fmt=".3f",
        linewidths=0.4
    )

    plt.title("Mutual IoC entre Páginas do Cluster")
    plt.tight_layout()

    out = csv_file.replace(".csv", "_heatmap.png")
    plt.savefig(out, dpi=250, bbox_inches="tight")
    plt.close()

    print(f"Cluster Mutual IoC heatmap saved: {out}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_rolling_ioc_from_log — rolling_ioc_analysis.txt
# ---------------------------------------------------------------------------

def plot_rolling_ioc_from_csv(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        print(f"No data found in {csv_file}")
        return

    # Change-point detection (PELT) if ruptures available
    rupture_results = []
    if rpt:
        print("\n--- STRUCTURAL CHANGE DETECTION (IoC Change Points) ---")
        for page, grp in df.groupby("Page"):
            if len(grp) > 15:
                try:
                    signal = grp["IoC"].values
                    algo   = rpt.Pelt(model="rbf").fit(signal)
                    breaks = algo.predict(pen=10)
                    if len(breaks) > 1:
                        print(f"  [{page}] Possible change points: {breaks}")
                    rupture_results.append({"Page": page, "Breaks": breaks[:-1]})
                except Exception:
                    pass
        pd.DataFrame(rupture_results).to_csv(
            os.path.join(os.path.dirname(csv_file), "ioc_ruptures.csv"), index=False
        )

    out_dir = os.path.join(os.path.dirname(csv_file) or ".", "rolling_plots")
    os.makedirs(out_dir, exist_ok=True)

    for page, grp in df.groupby("Page"):
        grp = grp.sort_values("Position")
        plt.figure(figsize=(15, 5))
        plt.plot(grp["Position"], grp["IoC"], marker="o", linestyle="-", markersize=2, color="crimson", linewidth=1)
        plt.axhline(y=0.03448, color="gray",  linestyle="--", label="Random (1/29 ≈ 0.034)")
        plt.axhline(y=0.0667, color="green", linestyle="--", label="Target (Liber ≈ 0.067)")
        plt.fill_between(grp["Position"], grp["IoC"], color="crimson", alpha=0.1)
        plt.title(f"Rolling IoC Metrics: {page}", fontsize=14)
        plt.xlabel("Window position (starting rune)")
        plt.ylabel("Index of Coincidence")
        plt.legend(loc="upper right")
        plt.ylim(0.0, 0.15) # Zoom out para ver referências com mais perspectiva
        plt.grid(True, alpha=0.3)
        # Sanitização de nome de arquivo para evitar problemas com caracteres especiais
        clean_name = re.sub(r'[^\w\-_\.]', '_', page)
        plt.savefig(
            os.path.join(out_dir, f"ioc_{clean_name}.png"), dpi=150, bbox_inches="tight"
        )
        plt.close()

    print(f"Rolling IoC plots saved in: {out_dir}")
    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_kasiski — kasiski_results.txt
# ---------------------------------------------------------------------------

def plot_kasiski_summary(txt_file: str, cache: dict) -> None:
    """Extract GCDs from a Kasiski results file and plot the distribution."""
    if not needs_processing(txt_file, cache):
        return
    if not os.path.exists(txt_file):
        return

    gcds: list = []
    with open(txt_file, "r", encoding="utf-8") as f:
        for line in f:
            m = re.search(r"GCD of deltas:\s*(\d+)", line)
            if m:
                gcd_val = int(m.group(1))
                if gcd_val > 1:
                    gcds.append(gcd_val)

    if not gcds:
        print(f"No GCDs extracted from {txt_file}")
        mark_processed(txt_file, cache)
        return

    from collections import Counter
    gcd_counts = Counter(gcds)
    labels, values = zip(*sorted(gcd_counts.items()))

    plt.figure(figsize=(12, 5))
    plt.bar([str(l) for l in labels], values, color="#4e79a7")
    plt.xlabel("GCD dos Deltas")
    plt.ylabel("Occurrences")
    plt.title("Kasiski: Distribution of GCDs (candidate key lengths)")
    plt.tight_layout()
    out = txt_file.replace(".txt", "_gcd_dist.png")
    plt.savefig(out, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Kasiski GCD plot saved: {out}")

    mark_processed(txt_file, cache)

# ---------------------------------------------------------------------------
# plot_entropy_vs_ioc — heuristic_scores.csv + analysis.txt
# ---------------------------------------------------------------------------

def plot_entropy_vs_ioc(heuristic_csv: str, analysis_txt: str, cache: dict) -> None:
    key = f"{heuristic_csv}|{analysis_txt}"
    # Cache baseado nos dois arquivos de entrada
    h_changed   = needs_processing(heuristic_csv, cache)
    txt_changed  = needs_processing(analysis_txt, cache)
    if not h_changed and not txt_changed:
        print(f"[CACHE HIT] entropy_vs_ioc — no input files changed, skipping.")
        return

    if not os.path.exists(heuristic_csv) or not os.path.exists(analysis_txt):
        return

    h_df        = pd.read_csv(heuristic_csv)
    entropy_data: dict = {}
    with open(analysis_txt, "r", encoding="utf-8") as f:
        current_page = None
        for line in f:
            if line.startswith("Page: "):
                current_page = line.split(": ")[1].split(" (")[0].strip()
            elif "Entropy:" in line and current_page:
                m = re.search(r"Entropy:\s+([\d.]+)", line)
                if m:
                    entropy_data[current_page] = float(m.group(1))

    h_df["Entropy"] = h_df["Page"].map(entropy_data)
    h_df = h_df.dropna(subset=["Entropy"])
    if h_df.empty:
        return

    plt.figure(figsize=(10, 8))
    scatter = plt.scatter(
        h_df["IoC"], h_df["Entropy"],
        c=h_df["Fitness"], cmap="viridis", s=100, alpha=0.7,
    )
    plt.colorbar(scatter, label="Fitness Score")
    plt.axvline(x=0.034, color="r", linestyle="--", alpha=0.3, label="Random IoC")
    plt.axvline(x=0.067, color="g", linestyle="--", alpha=0.3, label="Plaintext IoC")
    for i, txt in enumerate(h_df["Page"]):
        plt.annotate(txt, (h_df["IoC"].iloc[i], h_df["Entropy"].iloc[i]), fontsize=8, alpha=0.8)
    plt.title("Cripto-Assinatura: Entropia vs Index of Coincidence", fontsize=14)
    plt.xlabel("Index of Coincidence (IoC)")
    plt.ylabel("Entropia (Bits por Runa)")
    plt.grid(True, alpha=0.2)
    out = heuristic_csv.replace(".csv", "_entropy_ioc.png")
    plt.savefig(out, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Plot Entropia vs IoC salvo: {out}")

    mark_processed(heuristic_csv, cache)
    mark_processed(analysis_txt, cache)

# ---------------------------------------------------------------------------
# plot_zipf_law_analysis — liber_unigram_target.csv
# ---------------------------------------------------------------------------

def plot_zipf_law_analysis(csv_file: str, cache: dict) -> None:
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df    = pd.read_csv(csv_file)
    freqs = sorted(df["Frequency"].values, reverse=True)
    ranks = np.arange(1, len(freqs) + 1)

    plt.figure(figsize=(8, 6))
    plt.loglog(ranks, freqs, marker="o", linestyle="none", label="Liber Primus Distribution")
    plt.loglog(ranks, freqs[0] / ranks, linestyle="--", color="gray", alpha=0.5, label="Ideal Zipf (s=1)")
    plt.title("Zipf Analysis (Resolved Pages)", fontsize=14)
    plt.xlabel("Rank (Log)")
    plt.ylabel("Frequência (Log)")
    plt.legend()
    plt.grid(True, which="both", ls="-", alpha=0.1)
    out = csv_file.replace(".csv", "_zipf.png")
    plt.savefig(out, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Zipf analysis saved: {out}")

    # Não chama mark_processed aqui pois plot_unigram_distribution já o fez/fará

# ---------------------------------------------------------------------------
# plot_delta_autocorrelation — delta_autocorrelation.csv (NOVO)
# ---------------------------------------------------------------------------

def plot_delta_autocorrelation(csv_file: str, cache: dict) -> None:
    """Generate line plots for delta autocorrelation (search for periodicity)."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    out_dir = os.path.join(os.path.dirname(csv_file), "delta_autocorr_plots")
    os.makedirs(out_dir, exist_ok=True)

    for page_name, grp in df.groupby("Page"):
        plt.figure(figsize=(14, 4))
        plt.plot(grp["Lag"], grp["Score"], marker='o', markersize=3, linestyle='-', color='indigo')
        
        # Highlight multiples of 29 (rune alphabet size)
        max_lag = grp["Lag"].max()
        for mult in range(29, max_lag + 1, 29):
            plt.axvline(x=mult, color="orange", linestyle="--", alpha=0.5)
            
        # Destacar o lag com o maior score (ignorando lag 1 e 2 que costumam ser ruído de doublet)
        valid_lags = grp[grp["Lag"] > 2]
        if not valid_lags.empty:
            best_lag = valid_lags.loc[valid_lags["Score"].idxmax()]
            if best_lag["Score"] > 0.05: # Threshold sensível
                plt.axvline(x=best_lag["Lag"], color="red", linestyle=":", alpha=0.8, 
                            label=f"Pico: Lag {int(best_lag['Lag'])} (Score: {best_lag['Score']:.3f})")
                plt.legend()

        plt.title(f"Delta Autocorrelation (Crypto-Periodicity): {page_name}", fontsize=13)
        plt.xlabel("Lag (shift)")
        plt.ylabel("Score (match rate)")
        plt.grid(True, alpha=0.3)
        
        clean = str(page_name).replace(" ", "_")
        out = os.path.join(out_dir, f"delta_autocorr_{clean}.png")
        plt.savefig(out, dpi=150, bbox_inches="tight")
        plt.close()

    print(f"Delta autocorrelation plots saved in: {out_dir}")
    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# plot_delta_stream_dist — delta_stream_analysis.csv (NOVO)
# ---------------------------------------------------------------------------

def plot_delta_stream_dist(csv_file: str, cache: dict) -> None:
    """Generate histograms for the frequency of Delta Stream values (0-28)."""
    if not needs_processing(csv_file, cache):
        return
    if not os.path.exists(csv_file):
        return

    df = pd.read_csv(csv_file)
    if df.empty:
        return

    # Histograma Global de Deltas
    plt.figure(figsize=(10, 5))
    sns.countplot(data=df, x="Delta", hue="Delta", palette="viridis", legend=False)
    plt.title("Global Distribution of Delta Stream Values (0-28)", fontsize=14)
    plt.xlabel("Delta value (C[i] - C[i-1])")
    plt.ylabel("Frequency")
    
    out_global = csv_file.replace(".csv", "_global_dist.png")
    plt.savefig(out_global, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Global delta stream distribution saved: {out_global}")

    mark_processed(csv_file, cache)

# ---------------------------------------------------------------------------
# generate_master_summary — todos os .txt
# ---------------------------------------------------------------------------

def generate_master_summary(output_dir: str, cache: dict) -> None:
    txt_files    = glob.glob(os.path.join(output_dir, "*.txt"))
    summary_path = os.path.join(output_dir, "MASTER_RESEARCH_SUMMARY.log")
    keywords     = ["HIT", "Anomaly", "[!]", "STRONG", "Cluster found", "Pattern ["]

    # Verifica se algum txt mudou antes de regenerar
    any_changed = any(needs_processing(p, cache) for p in txt_files)
    if not any_changed:
        print("[CACHE HIT] MASTER_RESEARCH_SUMMARY — no .txt changed, skipping.")
        return

    print(f"Generating master summary at {summary_path}...")
    with open(summary_path, "w", encoding="utf-8") as master:
        master.write("=== CICADA 3301 RESEARCH: MASTER ANALYTICAL SUMMARY ===\n")
        master.write(f"Generation date: {pd.Timestamp.now()}\n\n")

        for f_path in txt_files:
            fname = os.path.basename(f_path)
            if "MASTER_RESEARCH_SUMMARY" in fname or "_report.txt" in fname:
                continue
            master.write(f"\n>>> ARQUIVO: {fname}\n")
            try:
                with open(f_path, "r", encoding="utf-8") as f:
                    lines = f.readlines()
                relevant = [l.strip() for l in lines if any(k in l for k in keywords)]
                if relevant:
                    master.write(f"Total points of interest: {len(relevant)}\n")
                    for rl in relevant[:15]:
                        master.write(f"  [LOG] {rl}\n")
                    if len(relevant) > 15:
                        master.write(f"  ... and {len(relevant)-15} more entries.\n")
                else:
                    master.write("No immediate critical patterns detected.\n")
            except Exception as exc:
                master.write(f"Error reading file: {exc}\n")

    # Registra todos os txts como processados
    for p in txt_files:
        if os.path.exists(p):
            mark_processed(p, cache)

if __name__ == "__main__":
    OUTPUT_DIR = "../output"
    if not os.path.exists(OUTPUT_DIR):
        print(f"Folder {OUTPUT_DIR} not found. Run the C++ code first.")
        exit(1)

    # Load hash cache from disk
    cache = _load_cache()

    print("Starting full data scan (with SHA-256 cache)...\n")

    # --- CSVs de correlação ---
    for csv_path in glob.glob(os.path.join(OUTPUT_DIR, "corr_*.csv")):
        plot_correlation_matrix(csv_path, cache)

    # --- Deltas de interrupções ---
    for csv_path in glob.glob(os.path.join(OUTPUT_DIR, "interrupt_deltas*.csv")):
        plot_delta_histograms(csv_path, cache)

    # --- Distribuição unigrama alvo ---
    unigram_csv = os.path.join(OUTPUT_DIR, "liber_unigram_target.csv")
    plot_unigram_distribution(unigram_csv, cache)
    plot_zipf_law_analysis(unigram_csv, cache)

    # --- Heurísticas de cifra ---
    heuristic_csv = os.path.join(OUTPUT_DIR, "heuristic_scores.csv")
    plot_heuristic_summary(heuristic_csv, cache)

    # --- Key stream ---
    ks_csv = os.path.join(OUTPUT_DIR, "key_stream_analysis.csv")
    plot_key_stream_analysis(ks_csv, cache)

    # --- Page features (novo) ---
    feat_csv = os.path.join(OUTPUT_DIR, "page_features.csv")
    plot_page_features(feat_csv, cache)

    # --- Friedman scan (novo) ---
    friedman_csv = os.path.join(OUTPUT_DIR, "friedman_scan.csv")
    plot_friedman_scan(friedman_csv, cache)

    # --- Cluster Mutual IoC (novo) ---
    cluster_csv = os.path.join(OUTPUT_DIR, "cluster_mutual_ioc.csv")
    plot_cluster_mutual_ioc(cluster_csv, cache)

    # --- Rolling IoC (CSV de dados completos) ---
    rolling_ioc_csv = os.path.join(OUTPUT_DIR, "rolling_ioc_peaks.csv")
    plot_rolling_ioc_from_csv(rolling_ioc_csv, cache)

    # --- Kasiski (log de texto, novo) ---
    kasiski_txt = os.path.join(OUTPUT_DIR, "kasiski_results.txt")
    plot_kasiski_summary(kasiski_txt, cache)

    # --- Entropia vs IoC cruzado ---
    analysis_txt = os.path.join(OUTPUT_DIR, "analysis.txt")
    plot_entropy_vs_ioc(heuristic_csv, analysis_txt, cache)

    # --- Delta Stream e Autocorrelação (NOVO) ---
    delta_stream_csv = os.path.join(OUTPUT_DIR, "delta_stream_analysis.csv")
    plot_delta_stream_dist(delta_stream_csv, cache)

    delta_autocorr_csv = os.path.join(OUTPUT_DIR, "delta_autocorrelation.csv")
    plot_delta_autocorrelation(delta_autocorr_csv, cache)

    # --- Resumo mestre de todos os .txt ---
    generate_master_summary(OUTPUT_DIR, cache)

    # Persiste o cache atualizado em disco
    _save_cache(cache)

    print("\n[SUCCESS] All files have been processed. Cache updated on", CACHE_FILE)